spring:
   datasource:
        url: jdbc:mysql://127.0.0.1:3306/easymis
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
  datasource:
      name: autosave
      url: jdbc:sqlserver://172.16.1.16:1433;DatabaseName=AirProvinceDB
      username: sa
      password: admin@123

#      url: jdbc:sqlserver://10.190.1.8:1433;DatabaseName=AirSouthwestDB
#      username: sa
#      password: xsscd@123
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  datasource2:
      name: autosave
      url: jdbc:sqlserver://172.16.1.16:1433;DatabaseName=AirSouthwestDB
      username: sa
      password: admin@123

#      url: jdbc:sqlserver://10.190.1.8:1433;DatabaseName=AirSouthwestDB
#      username: sa
#      password: xsscd@123
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#配置日志
logging:
  #采用相对路径方式将日志文件输出到
    file: log\southwest.log
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  #配置日志文件路径
    level:
        root: ERROR
        xsscd.monitor.air.southwest: debug #不同目录下的日志可配置不同级别
        org.springfromework.web: ERROR
        org.hibernate: error
