##多数据源
datasource:
  #主库
  master:
    jdbcUrl: jdbc:mysql://localhost:3306/easymis?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #从库
  slave:
    #并非url而是jdbcUrl(因为这个在获取数据源时一直报错，看了DataSource的属性才知道是jdbcUrl)
    jdbcUrl: jdbc:mysql://localhost:3306/southwest?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#配置日志
logging:
  #采用相对路径方式将日志文件输出到
    file: log\southwest.log
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  #配置日志文件路径
    level:
        root: debug
        xsscd.monitor.air.southwest: debug #不同目录下的日志可配置不同级别
        org.springfromework.web: ERROR
        org.hibernate: error