package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

public class AQIStationRealTimeDataPublishHistory extends AQIStationRealTimeDataPublishHistoryKey {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.CO_1h
     *
     * @mbggenerated
     */
    private String cO1h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.NO2_1h
     *
     * @mbggenerated
     */
    private String nO21h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.O3_1h
     *
     * @mbggenerated
     */
    private String o31h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.PM10_1h
     *
     * @mbggenerated
     */
    private String pM101h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.PM2_5_1h
     *
     * @mbggenerated
     */
    private String pM251h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.SO2_1h
     *
     * @mbggenerated
     */
    private String sO21h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.AQI
     *
     * @mbggenerated
     */
    private String aQI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.PrimaryPollutant
     *
     * @mbggenerated
     */
    private String primaryPollutant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.ICO_1h
     *
     * @mbggenerated
     */
    private String iCO1h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.INO2_1h
     *
     * @mbggenerated
     */
    private String iNO21h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.IO3_1h
     *
     * @mbggenerated
     */
    private String iO31h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.IPM10_1h
     *
     * @mbggenerated
     */
    private String iPM101h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.IPM2_5_1h
     *
     * @mbggenerated
     */
    private String iPM251h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.ISO2_1h
     *
     * @mbggenerated
     */
    private String iSO21h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationRealTimeDataPublishHistory.StationName
     *
     * @mbggenerated
     */
    private String stationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.CO_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.CO_1h
     *
     * @mbggenerated
     */
    public String getcO1h() {
        return cO1h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.CO_1h
     *
     * @param cO1h the value for AQIStationRealTimeDataPublishHistory.CO_1h
     *
     * @mbggenerated
     */
    public void setcO1h(String cO1h) {
        this.cO1h = cO1h == null ? null : cO1h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.NO2_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.NO2_1h
     *
     * @mbggenerated
     */
    public String getnO21h() {
        return nO21h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.NO2_1h
     *
     * @param nO21h the value for AQIStationRealTimeDataPublishHistory.NO2_1h
     *
     * @mbggenerated
     */
    public void setnO21h(String nO21h) {
        this.nO21h = nO21h == null ? null : nO21h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.O3_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.O3_1h
     *
     * @mbggenerated
     */
    public String getO31h() {
        return o31h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.O3_1h
     *
     * @param o31h the value for AQIStationRealTimeDataPublishHistory.O3_1h
     *
     * @mbggenerated
     */
    public void setO31h(String o31h) {
        this.o31h = o31h == null ? null : o31h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.PM10_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.PM10_1h
     *
     * @mbggenerated
     */
    public String getpM101h() {
        return pM101h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.PM10_1h
     *
     * @param pM101h the value for AQIStationRealTimeDataPublishHistory.PM10_1h
     *
     * @mbggenerated
     */
    public void setpM101h(String pM101h) {
        this.pM101h = pM101h == null ? null : pM101h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.PM2_5_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.PM2_5_1h
     *
     * @mbggenerated
     */
    public String getpM251h() {
        return pM251h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.PM2_5_1h
     *
     * @param pM251h the value for AQIStationRealTimeDataPublishHistory.PM2_5_1h
     *
     * @mbggenerated
     */
    public void setpM251h(String pM251h) {
        this.pM251h = pM251h == null ? null : pM251h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.SO2_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.SO2_1h
     *
     * @mbggenerated
     */
    public String getsO21h() {
        return sO21h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.SO2_1h
     *
     * @param sO21h the value for AQIStationRealTimeDataPublishHistory.SO2_1h
     *
     * @mbggenerated
     */
    public void setsO21h(String sO21h) {
        this.sO21h = sO21h == null ? null : sO21h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.AQI
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.AQI
     *
     * @mbggenerated
     */
    public String getaQI() {
        return aQI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.AQI
     *
     * @param aQI the value for AQIStationRealTimeDataPublishHistory.AQI
     *
     * @mbggenerated
     */
    public void setaQI(String aQI) {
        this.aQI = aQI == null ? null : aQI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.PrimaryPollutant
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.PrimaryPollutant
     *
     * @mbggenerated
     */
    public String getPrimaryPollutant() {
        return primaryPollutant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.PrimaryPollutant
     *
     * @param primaryPollutant the value for AQIStationRealTimeDataPublishHistory.PrimaryPollutant
     *
     * @mbggenerated
     */
    public void setPrimaryPollutant(String primaryPollutant) {
        this.primaryPollutant = primaryPollutant == null ? null : primaryPollutant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.ICO_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.ICO_1h
     *
     * @mbggenerated
     */
    public String getiCO1h() {
        return iCO1h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.ICO_1h
     *
     * @param iCO1h the value for AQIStationRealTimeDataPublishHistory.ICO_1h
     *
     * @mbggenerated
     */
    public void setiCO1h(String iCO1h) {
        this.iCO1h = iCO1h == null ? null : iCO1h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.INO2_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.INO2_1h
     *
     * @mbggenerated
     */
    public String getiNO21h() {
        return iNO21h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.INO2_1h
     *
     * @param iNO21h the value for AQIStationRealTimeDataPublishHistory.INO2_1h
     *
     * @mbggenerated
     */
    public void setiNO21h(String iNO21h) {
        this.iNO21h = iNO21h == null ? null : iNO21h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.IO3_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.IO3_1h
     *
     * @mbggenerated
     */
    public String getiO31h() {
        return iO31h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.IO3_1h
     *
     * @param iO31h the value for AQIStationRealTimeDataPublishHistory.IO3_1h
     *
     * @mbggenerated
     */
    public void setiO31h(String iO31h) {
        this.iO31h = iO31h == null ? null : iO31h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.IPM10_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.IPM10_1h
     *
     * @mbggenerated
     */
    public String getiPM101h() {
        return iPM101h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.IPM10_1h
     *
     * @param iPM101h the value for AQIStationRealTimeDataPublishHistory.IPM10_1h
     *
     * @mbggenerated
     */
    public void setiPM101h(String iPM101h) {
        this.iPM101h = iPM101h == null ? null : iPM101h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.IPM2_5_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.IPM2_5_1h
     *
     * @mbggenerated
     */
    public String getiPM251h() {
        return iPM251h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.IPM2_5_1h
     *
     * @param iPM251h the value for AQIStationRealTimeDataPublishHistory.IPM2_5_1h
     *
     * @mbggenerated
     */
    public void setiPM251h(String iPM251h) {
        this.iPM251h = iPM251h == null ? null : iPM251h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.ISO2_1h
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.ISO2_1h
     *
     * @mbggenerated
     */
    public String getiSO21h() {
        return iSO21h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.ISO2_1h
     *
     * @param iSO21h the value for AQIStationRealTimeDataPublishHistory.ISO2_1h
     *
     * @mbggenerated
     */
    public void setiSO21h(String iSO21h) {
        this.iSO21h = iSO21h == null ? null : iSO21h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationRealTimeDataPublishHistory.StationName
     *
     * @return the value of AQIStationRealTimeDataPublishHistory.StationName
     *
     * @mbggenerated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationRealTimeDataPublishHistory.StationName
     *
     * @param stationName the value for AQIStationRealTimeDataPublishHistory.StationName
     *
     * @mbggenerated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }
}