package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class AQIStationDayDataPublishHistoryKey {
	private static final long serialVersionUID = 1L;

    private String cityName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationDayDataPublishHistory.TimePoint
     *
     * @mbggenerated
     */
    private Date timePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AQIStationDayDataPublishHistory.StationCode
     *
     * @mbggenerated
     */
    private String stationCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationDayDataPublishHistory.TimePoint
     *
     * @return the value of AQIStationDayDataPublishHistory.TimePoint
     *
     * @mbggenerated
     */
    public Date getTimePoint() {
        return timePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationDayDataPublishHistory.TimePoint
     *
     * @param timePoint the value for AQIStationDayDataPublishHistory.TimePoint
     *
     * @mbggenerated
     */
    public void setTimePoint(Date timePoint) {
        this.timePoint = timePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AQIStationDayDataPublishHistory.StationCode
     *
     * @return the value of AQIStationDayDataPublishHistory.StationCode
     *
     * @mbggenerated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AQIStationDayDataPublishHistory.StationCode
     *
     * @param stationCode the value for AQIStationDayDataPublishHistory.StationCode
     *
     * @mbggenerated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
}