package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class ExpertForcastDataView {
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.predict_time
     *
     * @mbggenerated
     */
    private Date predictTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.forcast_time
     *
     * @mbggenerated
     */
    private Date forcastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.forcast_day
     *
     * @mbggenerated
     */
    private Integer forcastDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.station
     *
     * @mbggenerated
     */
    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.station_code
     *
     * @mbggenerated
     */
    private String stationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.county
     *
     * @mbggenerated
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.county_code
     *
     * @mbggenerated
     */
    private String countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.PM25_R
     *
     * @mbggenerated
     */
    private String pM25R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.PM25_Y
     *
     * @mbggenerated
     */
    private String pM25Y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.AQI_R
     *
     * @mbggenerated
     */
    private String aQIR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.AQI_Y_ST
     *
     * @mbggenerated
     */
    private String aQIYST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_forcast_data_view.AQI_Y_ED
     *
     * @mbggenerated
     */
    private String aQIYED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.id
     *
     * @return the value of expert_forcast_data_view.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.id
     *
     * @param id the value for expert_forcast_data_view.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.predict_time
     *
     * @return the value of expert_forcast_data_view.predict_time
     *
     * @mbggenerated
     */
    public Date getPredictTime() {
        return predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.predict_time
     *
     * @param predictTime the value for expert_forcast_data_view.predict_time
     *
     * @mbggenerated
     */
    public void setPredictTime(Date predictTime) {
        this.predictTime = predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.forcast_time
     *
     * @return the value of expert_forcast_data_view.forcast_time
     *
     * @mbggenerated
     */
    public Date getForcastTime() {
        return forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.forcast_time
     *
     * @param forcastTime the value for expert_forcast_data_view.forcast_time
     *
     * @mbggenerated
     */
    public void setForcastTime(Date forcastTime) {
        this.forcastTime = forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.forcast_day
     *
     * @return the value of expert_forcast_data_view.forcast_day
     *
     * @mbggenerated
     */
    public Integer getForcastDay() {
        return forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.forcast_day
     *
     * @param forcastDay the value for expert_forcast_data_view.forcast_day
     *
     * @mbggenerated
     */
    public void setForcastDay(Integer forcastDay) {
        this.forcastDay = forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.province
     *
     * @return the value of expert_forcast_data_view.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.province
     *
     * @param province the value for expert_forcast_data_view.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.province_code
     *
     * @return the value of expert_forcast_data_view.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.province_code
     *
     * @param provinceCode the value for expert_forcast_data_view.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.city
     *
     * @return the value of expert_forcast_data_view.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.city
     *
     * @param city the value for expert_forcast_data_view.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.city_code
     *
     * @return the value of expert_forcast_data_view.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.city_code
     *
     * @param cityCode the value for expert_forcast_data_view.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.station
     *
     * @return the value of expert_forcast_data_view.station
     *
     * @mbggenerated
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.station
     *
     * @param station the value for expert_forcast_data_view.station
     *
     * @mbggenerated
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.station_code
     *
     * @return the value of expert_forcast_data_view.station_code
     *
     * @mbggenerated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.station_code
     *
     * @param stationCode the value for expert_forcast_data_view.station_code
     *
     * @mbggenerated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.county
     *
     * @return the value of expert_forcast_data_view.county
     *
     * @mbggenerated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.county
     *
     * @param county the value for expert_forcast_data_view.county
     *
     * @mbggenerated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.county_code
     *
     * @return the value of expert_forcast_data_view.county_code
     *
     * @mbggenerated
     */
    public String getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.county_code
     *
     * @param countyCode the value for expert_forcast_data_view.county_code
     *
     * @mbggenerated
     */
    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode == null ? null : countyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.PM25_R
     *
     * @return the value of expert_forcast_data_view.PM25_R
     *
     * @mbggenerated
     */
    public String getpM25R() {
        return pM25R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.PM25_R
     *
     * @param pM25R the value for expert_forcast_data_view.PM25_R
     *
     * @mbggenerated
     */
    public void setpM25R(String pM25R) {
        this.pM25R = pM25R == null ? null : pM25R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.PM25_Y
     *
     * @return the value of expert_forcast_data_view.PM25_Y
     *
     * @mbggenerated
     */
    public String getpM25Y() {
        return pM25Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.PM25_Y
     *
     * @param pM25Y the value for expert_forcast_data_view.PM25_Y
     *
     * @mbggenerated
     */
    public void setpM25Y(String pM25Y) {
        this.pM25Y = pM25Y == null ? null : pM25Y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.AQI_R
     *
     * @return the value of expert_forcast_data_view.AQI_R
     *
     * @mbggenerated
     */
    public String getaQIR() {
        return aQIR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.AQI_R
     *
     * @param aQIR the value for expert_forcast_data_view.AQI_R
     *
     * @mbggenerated
     */
    public void setaQIR(String aQIR) {
        this.aQIR = aQIR == null ? null : aQIR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.AQI_Y_ST
     *
     * @return the value of expert_forcast_data_view.AQI_Y_ST
     *
     * @mbggenerated
     */
    public String getaQIYST() {
        return aQIYST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.AQI_Y_ST
     *
     * @param aQIYST the value for expert_forcast_data_view.AQI_Y_ST
     *
     * @mbggenerated
     */
    public void setaQIYST(String aQIYST) {
        this.aQIYST = aQIYST == null ? null : aQIYST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_forcast_data_view.AQI_Y_ED
     *
     * @return the value of expert_forcast_data_view.AQI_Y_ED
     *
     * @mbggenerated
     */
    public String getaQIYED() {
        return aQIYED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_forcast_data_view.AQI_Y_ED
     *
     * @param aQIYED the value for expert_forcast_data_view.AQI_Y_ED
     *
     * @mbggenerated
     */
    public void setaQIYED(String aQIYED) {
        this.aQIYED = aQIYED == null ? null : aQIYED.trim();
    }
}