package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class ExpertFirstPollutant {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.predict_time
     *
     * @mbggenerated
     */
    private Date predictTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.forcast_time
     *
     * @mbggenerated
     */
    private Date forcastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.forcast_day
     *
     * @mbggenerated
     */
    private Integer forcastDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.station
     *
     * @mbggenerated
     */
    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.station_code
     *
     * @mbggenerated
     */
    private String stationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.county
     *
     * @mbggenerated
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.county_code
     *
     * @mbggenerated
     */
    private String countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.PM2_5_R
     *
     * @mbggenerated
     */
    private String pM25R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.O3_8h_R
     *
     * @mbggenerated
     */
    private String o38hR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.SO2_R
     *
     * @mbggenerated
     */
    private String sO2R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.NO2_R
     *
     * @mbggenerated
     */
    private String nO2R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.CO_R
     *
     * @mbggenerated
     */
    private String cOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.PM_10_R
     *
     * @mbggenerated
     */
    private String pM10R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.IS_NONE_R
     *
     * @mbggenerated
     */
    private String iSNONER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.PM2_5_Y
     *
     * @mbggenerated
     */
    private String pM25Y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.O3_8h_Y
     *
     * @mbggenerated
     */
    private String o38hY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.SO2_Y
     *
     * @mbggenerated
     */
    private String sO2Y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.NO2_Y
     *
     * @mbggenerated
     */
    private String nO2Y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.CO_Y
     *
     * @mbggenerated
     */
    private String cOY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.PM_10_Y
     *
     * @mbggenerated
     */
    private String pM10Y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_first_pollutant.IS_NONE_Y
     *
     * @mbggenerated
     */
    private String iSNONEY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.id
     *
     * @return the value of expert_first_pollutant.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.id
     *
     * @param id the value for expert_first_pollutant.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.predict_time
     *
     * @return the value of expert_first_pollutant.predict_time
     *
     * @mbggenerated
     */
    public Date getPredictTime() {
        return predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.predict_time
     *
     * @param predictTime the value for expert_first_pollutant.predict_time
     *
     * @mbggenerated
     */
    public void setPredictTime(Date predictTime) {
        this.predictTime = predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.forcast_time
     *
     * @return the value of expert_first_pollutant.forcast_time
     *
     * @mbggenerated
     */
    public Date getForcastTime() {
        return forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.forcast_time
     *
     * @param forcastTime the value for expert_first_pollutant.forcast_time
     *
     * @mbggenerated
     */
    public void setForcastTime(Date forcastTime) {
        this.forcastTime = forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.forcast_day
     *
     * @return the value of expert_first_pollutant.forcast_day
     *
     * @mbggenerated
     */
    public Integer getForcastDay() {
        return forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.forcast_day
     *
     * @param forcastDay the value for expert_first_pollutant.forcast_day
     *
     * @mbggenerated
     */
    public void setForcastDay(Integer forcastDay) {
        this.forcastDay = forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.province
     *
     * @return the value of expert_first_pollutant.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.province
     *
     * @param province the value for expert_first_pollutant.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.province_code
     *
     * @return the value of expert_first_pollutant.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.province_code
     *
     * @param provinceCode the value for expert_first_pollutant.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.city
     *
     * @return the value of expert_first_pollutant.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.city
     *
     * @param city the value for expert_first_pollutant.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.city_code
     *
     * @return the value of expert_first_pollutant.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.city_code
     *
     * @param cityCode the value for expert_first_pollutant.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.station
     *
     * @return the value of expert_first_pollutant.station
     *
     * @mbggenerated
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.station
     *
     * @param station the value for expert_first_pollutant.station
     *
     * @mbggenerated
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.station_code
     *
     * @return the value of expert_first_pollutant.station_code
     *
     * @mbggenerated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.station_code
     *
     * @param stationCode the value for expert_first_pollutant.station_code
     *
     * @mbggenerated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.county
     *
     * @return the value of expert_first_pollutant.county
     *
     * @mbggenerated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.county
     *
     * @param county the value for expert_first_pollutant.county
     *
     * @mbggenerated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.county_code
     *
     * @return the value of expert_first_pollutant.county_code
     *
     * @mbggenerated
     */
    public String getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.county_code
     *
     * @param countyCode the value for expert_first_pollutant.county_code
     *
     * @mbggenerated
     */
    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode == null ? null : countyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.PM2_5_R
     *
     * @return the value of expert_first_pollutant.PM2_5_R
     *
     * @mbggenerated
     */
    public String getpM25R() {
        return pM25R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.PM2_5_R
     *
     * @param pM25R the value for expert_first_pollutant.PM2_5_R
     *
     * @mbggenerated
     */
    public void setpM25R(String pM25R) {
        this.pM25R = pM25R == null ? null : pM25R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.O3_8h_R
     *
     * @return the value of expert_first_pollutant.O3_8h_R
     *
     * @mbggenerated
     */
    public String getO38hR() {
        return o38hR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.O3_8h_R
     *
     * @param o38hR the value for expert_first_pollutant.O3_8h_R
     *
     * @mbggenerated
     */
    public void setO38hR(String o38hR) {
        this.o38hR = o38hR == null ? null : o38hR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.SO2_R
     *
     * @return the value of expert_first_pollutant.SO2_R
     *
     * @mbggenerated
     */
    public String getsO2R() {
        return sO2R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.SO2_R
     *
     * @param sO2R the value for expert_first_pollutant.SO2_R
     *
     * @mbggenerated
     */
    public void setsO2R(String sO2R) {
        this.sO2R = sO2R == null ? null : sO2R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.NO2_R
     *
     * @return the value of expert_first_pollutant.NO2_R
     *
     * @mbggenerated
     */
    public String getnO2R() {
        return nO2R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.NO2_R
     *
     * @param nO2R the value for expert_first_pollutant.NO2_R
     *
     * @mbggenerated
     */
    public void setnO2R(String nO2R) {
        this.nO2R = nO2R == null ? null : nO2R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.CO_R
     *
     * @return the value of expert_first_pollutant.CO_R
     *
     * @mbggenerated
     */
    public String getcOR() {
        return cOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.CO_R
     *
     * @param cOR the value for expert_first_pollutant.CO_R
     *
     * @mbggenerated
     */
    public void setcOR(String cOR) {
        this.cOR = cOR == null ? null : cOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.PM_10_R
     *
     * @return the value of expert_first_pollutant.PM_10_R
     *
     * @mbggenerated
     */
    public String getpM10R() {
        return pM10R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.PM_10_R
     *
     * @param pM10R the value for expert_first_pollutant.PM_10_R
     *
     * @mbggenerated
     */
    public void setpM10R(String pM10R) {
        this.pM10R = pM10R == null ? null : pM10R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.IS_NONE_R
     *
     * @return the value of expert_first_pollutant.IS_NONE_R
     *
     * @mbggenerated
     */
    public String getiSNONER() {
        return iSNONER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.IS_NONE_R
     *
     * @param iSNONER the value for expert_first_pollutant.IS_NONE_R
     *
     * @mbggenerated
     */
    public void setiSNONER(String iSNONER) {
        this.iSNONER = iSNONER == null ? null : iSNONER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.PM2_5_Y
     *
     * @return the value of expert_first_pollutant.PM2_5_Y
     *
     * @mbggenerated
     */
    public String getpM25Y() {
        return pM25Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.PM2_5_Y
     *
     * @param pM25Y the value for expert_first_pollutant.PM2_5_Y
     *
     * @mbggenerated
     */
    public void setpM25Y(String pM25Y) {
        this.pM25Y = pM25Y == null ? null : pM25Y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.O3_8h_Y
     *
     * @return the value of expert_first_pollutant.O3_8h_Y
     *
     * @mbggenerated
     */
    public String getO38hY() {
        return o38hY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.O3_8h_Y
     *
     * @param o38hY the value for expert_first_pollutant.O3_8h_Y
     *
     * @mbggenerated
     */
    public void setO38hY(String o38hY) {
        this.o38hY = o38hY == null ? null : o38hY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.SO2_Y
     *
     * @return the value of expert_first_pollutant.SO2_Y
     *
     * @mbggenerated
     */
    public String getsO2Y() {
        return sO2Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.SO2_Y
     *
     * @param sO2Y the value for expert_first_pollutant.SO2_Y
     *
     * @mbggenerated
     */
    public void setsO2Y(String sO2Y) {
        this.sO2Y = sO2Y == null ? null : sO2Y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.NO2_Y
     *
     * @return the value of expert_first_pollutant.NO2_Y
     *
     * @mbggenerated
     */
    public String getnO2Y() {
        return nO2Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.NO2_Y
     *
     * @param nO2Y the value for expert_first_pollutant.NO2_Y
     *
     * @mbggenerated
     */
    public void setnO2Y(String nO2Y) {
        this.nO2Y = nO2Y == null ? null : nO2Y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.CO_Y
     *
     * @return the value of expert_first_pollutant.CO_Y
     *
     * @mbggenerated
     */
    public String getcOY() {
        return cOY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.CO_Y
     *
     * @param cOY the value for expert_first_pollutant.CO_Y
     *
     * @mbggenerated
     */
    public void setcOY(String cOY) {
        this.cOY = cOY == null ? null : cOY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.PM_10_Y
     *
     * @return the value of expert_first_pollutant.PM_10_Y
     *
     * @mbggenerated
     */
    public String getpM10Y() {
        return pM10Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.PM_10_Y
     *
     * @param pM10Y the value for expert_first_pollutant.PM_10_Y
     *
     * @mbggenerated
     */
    public void setpM10Y(String pM10Y) {
        this.pM10Y = pM10Y == null ? null : pM10Y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_first_pollutant.IS_NONE_Y
     *
     * @return the value of expert_first_pollutant.IS_NONE_Y
     *
     * @mbggenerated
     */
    public String getiSNONEY() {
        return iSNONEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_first_pollutant.IS_NONE_Y
     *
     * @param iSNONEY the value for expert_first_pollutant.IS_NONE_Y
     *
     * @mbggenerated
     */
    public void setiSNONEY(String iSNONEY) {
        this.iSNONEY = iSNONEY == null ? null : iSNONEY.trim();
    }
}