package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class ExpertAirLvl {
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.predict_time
     *
     * @mbggenerated
     */
    private Date predictTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.forcast_time
     *
     * @mbggenerated
     */
    private Date forcastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.forcast_day
     *
     * @mbggenerated
     */
    private Integer forcastDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.station
     *
     * @mbggenerated
     */
    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.station_code
     *
     * @mbggenerated
     */
    private String stationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.county
     *
     * @mbggenerated
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.county_code
     *
     * @mbggenerated
     */
    private String countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv1_R
     *
     * @mbggenerated
     */
    private String lv1R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv2_R
     *
     * @mbggenerated
     */
    private String lv2R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv3_R
     *
     * @mbggenerated
     */
    private String lv3R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv4_R
     *
     * @mbggenerated
     */
    private String lv4R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv5_R
     *
     * @mbggenerated
     */
    private String lv5R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv6_R
     *
     * @mbggenerated
     */
    private String lv6R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv1_Y
     *
     * @mbggenerated
     */
    private String lv1Y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv2_Y
     *
     * @mbggenerated
     */
    private String lv2Y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv3_Y
     *
     * @mbggenerated
     */
    private String lv3Y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv4_Y
     *
     * @mbggenerated
     */
    private String lv4Y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv5_Y
     *
     * @mbggenerated
     */
    private String lv5Y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl.lv6_Y
     *
     * @mbggenerated
     */
    private String lv6Y;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.id
     *
     * @return the value of expert_air_lvl.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.id
     *
     * @param id the value for expert_air_lvl.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.predict_time
     *
     * @return the value of expert_air_lvl.predict_time
     *
     * @mbggenerated
     */
    public Date getPredictTime() {
        return predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.predict_time
     *
     * @param predictTime the value for expert_air_lvl.predict_time
     *
     * @mbggenerated
     */
    public void setPredictTime(Date predictTime) {
        this.predictTime = predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.forcast_time
     *
     * @return the value of expert_air_lvl.forcast_time
     *
     * @mbggenerated
     */
    public Date getForcastTime() {
        return forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.forcast_time
     *
     * @param forcastTime the value for expert_air_lvl.forcast_time
     *
     * @mbggenerated
     */
    public void setForcastTime(Date forcastTime) {
        this.forcastTime = forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.forcast_day
     *
     * @return the value of expert_air_lvl.forcast_day
     *
     * @mbggenerated
     */
    public Integer getForcastDay() {
        return forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.forcast_day
     *
     * @param forcastDay the value for expert_air_lvl.forcast_day
     *
     * @mbggenerated
     */
    public void setForcastDay(Integer forcastDay) {
        this.forcastDay = forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.province
     *
     * @return the value of expert_air_lvl.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.province
     *
     * @param province the value for expert_air_lvl.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.province_code
     *
     * @return the value of expert_air_lvl.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.province_code
     *
     * @param provinceCode the value for expert_air_lvl.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.city
     *
     * @return the value of expert_air_lvl.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.city
     *
     * @param city the value for expert_air_lvl.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.city_code
     *
     * @return the value of expert_air_lvl.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.city_code
     *
     * @param cityCode the value for expert_air_lvl.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.station
     *
     * @return the value of expert_air_lvl.station
     *
     * @mbggenerated
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.station
     *
     * @param station the value for expert_air_lvl.station
     *
     * @mbggenerated
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.station_code
     *
     * @return the value of expert_air_lvl.station_code
     *
     * @mbggenerated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.station_code
     *
     * @param stationCode the value for expert_air_lvl.station_code
     *
     * @mbggenerated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.county
     *
     * @return the value of expert_air_lvl.county
     *
     * @mbggenerated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.county
     *
     * @param county the value for expert_air_lvl.county
     *
     * @mbggenerated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.county_code
     *
     * @return the value of expert_air_lvl.county_code
     *
     * @mbggenerated
     */
    public String getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.county_code
     *
     * @param countyCode the value for expert_air_lvl.county_code
     *
     * @mbggenerated
     */
    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode == null ? null : countyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv1_R
     *
     * @return the value of expert_air_lvl.lv1_R
     *
     * @mbggenerated
     */
    public String getLv1R() {
        return lv1R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv1_R
     *
     * @param lv1R the value for expert_air_lvl.lv1_R
     *
     * @mbggenerated
     */
    public void setLv1R(String lv1R) {
        this.lv1R = lv1R == null ? null : lv1R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv2_R
     *
     * @return the value of expert_air_lvl.lv2_R
     *
     * @mbggenerated
     */
    public String getLv2R() {
        return lv2R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv2_R
     *
     * @param lv2R the value for expert_air_lvl.lv2_R
     *
     * @mbggenerated
     */
    public void setLv2R(String lv2R) {
        this.lv2R = lv2R == null ? null : lv2R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv3_R
     *
     * @return the value of expert_air_lvl.lv3_R
     *
     * @mbggenerated
     */
    public String getLv3R() {
        return lv3R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv3_R
     *
     * @param lv3R the value for expert_air_lvl.lv3_R
     *
     * @mbggenerated
     */
    public void setLv3R(String lv3R) {
        this.lv3R = lv3R == null ? null : lv3R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv4_R
     *
     * @return the value of expert_air_lvl.lv4_R
     *
     * @mbggenerated
     */
    public String getLv4R() {
        return lv4R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv4_R
     *
     * @param lv4R the value for expert_air_lvl.lv4_R
     *
     * @mbggenerated
     */
    public void setLv4R(String lv4R) {
        this.lv4R = lv4R == null ? null : lv4R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv5_R
     *
     * @return the value of expert_air_lvl.lv5_R
     *
     * @mbggenerated
     */
    public String getLv5R() {
        return lv5R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv5_R
     *
     * @param lv5R the value for expert_air_lvl.lv5_R
     *
     * @mbggenerated
     */
    public void setLv5R(String lv5R) {
        this.lv5R = lv5R == null ? null : lv5R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv6_R
     *
     * @return the value of expert_air_lvl.lv6_R
     *
     * @mbggenerated
     */
    public String getLv6R() {
        return lv6R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv6_R
     *
     * @param lv6R the value for expert_air_lvl.lv6_R
     *
     * @mbggenerated
     */
    public void setLv6R(String lv6R) {
        this.lv6R = lv6R == null ? null : lv6R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv1_Y
     *
     * @return the value of expert_air_lvl.lv1_Y
     *
     * @mbggenerated
     */
    public String getLv1Y() {
        return lv1Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv1_Y
     *
     * @param lv1Y the value for expert_air_lvl.lv1_Y
     *
     * @mbggenerated
     */
    public void setLv1Y(String lv1Y) {
        this.lv1Y = lv1Y == null ? null : lv1Y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv2_Y
     *
     * @return the value of expert_air_lvl.lv2_Y
     *
     * @mbggenerated
     */
    public String getLv2Y() {
        return lv2Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv2_Y
     *
     * @param lv2Y the value for expert_air_lvl.lv2_Y
     *
     * @mbggenerated
     */
    public void setLv2Y(String lv2Y) {
        this.lv2Y = lv2Y == null ? null : lv2Y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv3_Y
     *
     * @return the value of expert_air_lvl.lv3_Y
     *
     * @mbggenerated
     */
    public String getLv3Y() {
        return lv3Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv3_Y
     *
     * @param lv3Y the value for expert_air_lvl.lv3_Y
     *
     * @mbggenerated
     */
    public void setLv3Y(String lv3Y) {
        this.lv3Y = lv3Y == null ? null : lv3Y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv4_Y
     *
     * @return the value of expert_air_lvl.lv4_Y
     *
     * @mbggenerated
     */
    public String getLv4Y() {
        return lv4Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv4_Y
     *
     * @param lv4Y the value for expert_air_lvl.lv4_Y
     *
     * @mbggenerated
     */
    public void setLv4Y(String lv4Y) {
        this.lv4Y = lv4Y == null ? null : lv4Y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv5_Y
     *
     * @return the value of expert_air_lvl.lv5_Y
     *
     * @mbggenerated
     */
    public String getLv5Y() {
        return lv5Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv5_Y
     *
     * @param lv5Y the value for expert_air_lvl.lv5_Y
     *
     * @mbggenerated
     */
    public void setLv5Y(String lv5Y) {
        this.lv5Y = lv5Y == null ? null : lv5Y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl.lv6_Y
     *
     * @return the value of expert_air_lvl.lv6_Y
     *
     * @mbggenerated
     */
    public String getLv6Y() {
        return lv6Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl.lv6_Y
     *
     * @param lv6Y the value for expert_air_lvl.lv6_Y
     *
     * @mbggenerated
     */
    public void setLv6Y(String lv6Y) {
        this.lv6Y = lv6Y == null ? null : lv6Y.trim();
    }
}