package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class ExpertAirLvlCount {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.predict_time
     *
     * @mbggenerated
     */
    private Date predictTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.forcast_time
     *
     * @mbggenerated
     */
    private Date forcastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.forcast_day
     *
     * @mbggenerated
     */
    private Integer forcastDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.station
     *
     * @mbggenerated
     */
    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.station_code
     *
     * @mbggenerated
     */
    private String stationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.county
     *
     * @mbggenerated
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.county_code
     *
     * @mbggenerated
     */
    private String countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.expert_air_quality_R
     *
     * @mbggenerated
     */
    private String expertAirQualityR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.expert_first_pollutant_R
     *
     * @mbggenerated
     */
    private String expertFirstPollutantR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.expert_AQI_R
     *
     * @mbggenerated
     */
    private String expertAQIR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.expert_PM2_5_R
     *
     * @mbggenerated
     */
    private String expertPM25R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.expert_air_quality_Y
     *
     * @mbggenerated
     */
    private String expertAirQualityY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.expert_first_pollutant_Y
     *
     * @mbggenerated
     */
    private String expertFirstPollutantY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.expert_AQI_Y
     *
     * @mbggenerated
     */
    private String expertAQIY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_air_lvl_count.expert_PM2_5_Y
     *
     * @mbggenerated
     */
    private String expertPM25Y;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.id
     *
     * @return the value of expert_air_lvl_count.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.id
     *
     * @param id the value for expert_air_lvl_count.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.predict_time
     *
     * @return the value of expert_air_lvl_count.predict_time
     *
     * @mbggenerated
     */
    public Date getPredictTime() {
        return predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.predict_time
     *
     * @param predictTime the value for expert_air_lvl_count.predict_time
     *
     * @mbggenerated
     */
    public void setPredictTime(Date predictTime) {
        this.predictTime = predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.forcast_time
     *
     * @return the value of expert_air_lvl_count.forcast_time
     *
     * @mbggenerated
     */
    public Date getForcastTime() {
        return forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.forcast_time
     *
     * @param forcastTime the value for expert_air_lvl_count.forcast_time
     *
     * @mbggenerated
     */
    public void setForcastTime(Date forcastTime) {
        this.forcastTime = forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.forcast_day
     *
     * @return the value of expert_air_lvl_count.forcast_day
     *
     * @mbggenerated
     */
    public Integer getForcastDay() {
        return forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.forcast_day
     *
     * @param forcastDay the value for expert_air_lvl_count.forcast_day
     *
     * @mbggenerated
     */
    public void setForcastDay(Integer forcastDay) {
        this.forcastDay = forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.province
     *
     * @return the value of expert_air_lvl_count.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.province
     *
     * @param province the value for expert_air_lvl_count.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.province_code
     *
     * @return the value of expert_air_lvl_count.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.province_code
     *
     * @param provinceCode the value for expert_air_lvl_count.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.city
     *
     * @return the value of expert_air_lvl_count.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.city
     *
     * @param city the value for expert_air_lvl_count.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.city_code
     *
     * @return the value of expert_air_lvl_count.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.city_code
     *
     * @param cityCode the value for expert_air_lvl_count.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.station
     *
     * @return the value of expert_air_lvl_count.station
     *
     * @mbggenerated
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.station
     *
     * @param station the value for expert_air_lvl_count.station
     *
     * @mbggenerated
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.station_code
     *
     * @return the value of expert_air_lvl_count.station_code
     *
     * @mbggenerated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.station_code
     *
     * @param stationCode the value for expert_air_lvl_count.station_code
     *
     * @mbggenerated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.county
     *
     * @return the value of expert_air_lvl_count.county
     *
     * @mbggenerated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.county
     *
     * @param county the value for expert_air_lvl_count.county
     *
     * @mbggenerated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.county_code
     *
     * @return the value of expert_air_lvl_count.county_code
     *
     * @mbggenerated
     */
    public String getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.county_code
     *
     * @param countyCode the value for expert_air_lvl_count.county_code
     *
     * @mbggenerated
     */
    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode == null ? null : countyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.expert_air_quality_R
     *
     * @return the value of expert_air_lvl_count.expert_air_quality_R
     *
     * @mbggenerated
     */
    public String getExpertAirQualityR() {
        return expertAirQualityR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.expert_air_quality_R
     *
     * @param expertAirQualityR the value for expert_air_lvl_count.expert_air_quality_R
     *
     * @mbggenerated
     */
    public void setExpertAirQualityR(String expertAirQualityR) {
        this.expertAirQualityR = expertAirQualityR == null ? null : expertAirQualityR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.expert_first_pollutant_R
     *
     * @return the value of expert_air_lvl_count.expert_first_pollutant_R
     *
     * @mbggenerated
     */
    public String getExpertFirstPollutantR() {
        return expertFirstPollutantR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.expert_first_pollutant_R
     *
     * @param expertFirstPollutantR the value for expert_air_lvl_count.expert_first_pollutant_R
     *
     * @mbggenerated
     */
    public void setExpertFirstPollutantR(String expertFirstPollutantR) {
        this.expertFirstPollutantR = expertFirstPollutantR == null ? null : expertFirstPollutantR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.expert_AQI_R
     *
     * @return the value of expert_air_lvl_count.expert_AQI_R
     *
     * @mbggenerated
     */
    public String getExpertAQIR() {
        return expertAQIR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.expert_AQI_R
     *
     * @param expertAQIR the value for expert_air_lvl_count.expert_AQI_R
     *
     * @mbggenerated
     */
    public void setExpertAQIR(String expertAQIR) {
        this.expertAQIR = expertAQIR == null ? null : expertAQIR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.expert_PM2_5_R
     *
     * @return the value of expert_air_lvl_count.expert_PM2_5_R
     *
     * @mbggenerated
     */
    public String getExpertPM25R() {
        return expertPM25R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.expert_PM2_5_R
     *
     * @param expertPM25R the value for expert_air_lvl_count.expert_PM2_5_R
     *
     * @mbggenerated
     */
    public void setExpertPM25R(String expertPM25R) {
        this.expertPM25R = expertPM25R == null ? null : expertPM25R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.expert_air_quality_Y
     *
     * @return the value of expert_air_lvl_count.expert_air_quality_Y
     *
     * @mbggenerated
     */
    public String getExpertAirQualityY() {
        return expertAirQualityY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.expert_air_quality_Y
     *
     * @param expertAirQualityY the value for expert_air_lvl_count.expert_air_quality_Y
     *
     * @mbggenerated
     */
    public void setExpertAirQualityY(String expertAirQualityY) {
        this.expertAirQualityY = expertAirQualityY == null ? null : expertAirQualityY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.expert_first_pollutant_Y
     *
     * @return the value of expert_air_lvl_count.expert_first_pollutant_Y
     *
     * @mbggenerated
     */
    public String getExpertFirstPollutantY() {
        return expertFirstPollutantY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.expert_first_pollutant_Y
     *
     * @param expertFirstPollutantY the value for expert_air_lvl_count.expert_first_pollutant_Y
     *
     * @mbggenerated
     */
    public void setExpertFirstPollutantY(String expertFirstPollutantY) {
        this.expertFirstPollutantY = expertFirstPollutantY == null ? null : expertFirstPollutantY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.expert_AQI_Y
     *
     * @return the value of expert_air_lvl_count.expert_AQI_Y
     *
     * @mbggenerated
     */
    public String getExpertAQIY() {
        return expertAQIY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.expert_AQI_Y
     *
     * @param expertAQIY the value for expert_air_lvl_count.expert_AQI_Y
     *
     * @mbggenerated
     */
    public void setExpertAQIY(String expertAQIY) {
        this.expertAQIY = expertAQIY == null ? null : expertAQIY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_air_lvl_count.expert_PM2_5_Y
     *
     * @return the value of expert_air_lvl_count.expert_PM2_5_Y
     *
     * @mbggenerated
     */
    public String getExpertPM25Y() {
        return expertPM25Y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_air_lvl_count.expert_PM2_5_Y
     *
     * @param expertPM25Y the value for expert_air_lvl_count.expert_PM2_5_Y
     *
     * @mbggenerated
     */
    public void setExpertPM25Y(String expertPM25Y) {
        this.expertPM25Y = expertPM25Y == null ? null : expertPM25Y.trim();
    }
}