package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto.vo.SelectVO;

import java.util.Date;

public class ForcastDataView extends SelectVO{
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.forcast_type
     *
     * @mbggenerated
     */
    private String forcastType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.predict_time
     *
     * @mbggenerated
     */
    private Date predictTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.forcast_time
     *
     * @mbggenerated
     */
    private Date forcastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.forcast_day
     *
     * @mbggenerated
     */
    private Integer forcastDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.station
     *
     * @mbggenerated
     */
    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.station_code
     *
     * @mbggenerated
     */
    private String stationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.county
     *
     * @mbggenerated
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.county_code
     *
     * @mbggenerated
     */
    private String countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.AQI_R
     *
     * @mbggenerated
     */
    private String aQIR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.PM2_5_R
     *
     * @mbggenerated
     */
    private String pM25R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.PM10_R
     *
     * @mbggenerated
     */
    private String pM10R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.SO2_R
     *
     * @mbggenerated
     */
    private String sO2R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.NO2_R
     *
     * @mbggenerated
     */
    private String nO2R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.CO_R
     *
     * @mbggenerated
     */
    private String cOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.O3_R
     *
     * @mbggenerated
     */
    private String o3R;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.RH_R
     *
     * @mbggenerated
     */
    private String rHR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.Precipitation_R
     *
     * @mbggenerated
     */
    private String precipitationR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.Temperature_R
     *
     * @mbggenerated
     */
    private String temperatureR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.WindSpeed_R
     *
     * @mbggenerated
     */
    private String windSpeedR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.Pressure_R
     *
     * @mbggenerated
     */
    private String pressureR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.CloudCover_R
     *
     * @mbggenerated
     */
    private String cloudCoverR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.PBL_R
     *
     * @mbggenerated
     */
    private String pBLR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.WindDIR_R
     *
     * @mbggenerated
     */
    private String windDIRR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.AQI_C
     *
     * @mbggenerated
     */
    private String aQIC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.PM2_5_C
     *
     * @mbggenerated
     */
    private String pM25C;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.PM10_C
     *
     * @mbggenerated
     */
    private String pM10C;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.SO2_C
     *
     * @mbggenerated
     */
    private String sO2C;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.NO2_C
     *
     * @mbggenerated
     */
    private String nO2C;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.CO_C
     *
     * @mbggenerated
     */
    private String cOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.O3_C
     *
     * @mbggenerated
     */
    private String o3C;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.RH_C
     *
     * @mbggenerated
     */
    private String rHC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.Precipitation_C
     *
     * @mbggenerated
     */
    private String precipitationC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.Temperature_C
     *
     * @mbggenerated
     */
    private String temperatureC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.WindSpeed_C
     *
     * @mbggenerated
     */
    private String windSpeedC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.Pressure_C
     *
     * @mbggenerated
     */
    private String pressureC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.CloudCover_C
     *
     * @mbggenerated
     */
    private String cloudCoverC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.PBL_C
     *
     * @mbggenerated
     */
    private String pBLC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.WindDIR_C
     *
     * @mbggenerated
     */
    private String windDIRC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.AQI_O
     *
     * @mbggenerated
     */
    private String aQIO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.PM2_5_O
     *
     * @mbggenerated
     */
    private String pM25O;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.PM10_O
     *
     * @mbggenerated
     */
    private String pM10O;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.SO2_O
     *
     * @mbggenerated
     */
    private String sO2O;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.NO2_O
     *
     * @mbggenerated
     */
    private String nO2O;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.CO_O
     *
     * @mbggenerated
     */
    private String cOO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.O3_O
     *
     * @mbggenerated
     */
    private String o3O;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.RH_O
     *
     * @mbggenerated
     */
    private String rHO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.Precipitation_O
     *
     * @mbggenerated
     */
    private String precipitationO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.Temperature_O
     *
     * @mbggenerated
     */
    private String temperatureO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.WindSpeed_O
     *
     * @mbggenerated
     */
    private String windSpeedO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.Pressure_O
     *
     * @mbggenerated
     */
    private String pressureO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.CloudCover_O
     *
     * @mbggenerated
     */
    private String cloudCoverO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.PBL_O
     *
     * @mbggenerated
     */
    private String pBLO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forcast_data_view.WindDIR_O
     *
     * @mbggenerated
     */
    private String windDIRO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.id
     *
     * @return the value of forcast_data_view.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.id
     *
     * @param id the value for forcast_data_view.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.forcast_type
     *
     * @return the value of forcast_data_view.forcast_type
     *
     * @mbggenerated
     */
    public String getForcastType() {
        return forcastType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.forcast_type
     *
     * @param forcastType the value for forcast_data_view.forcast_type
     *
     * @mbggenerated
     */
    public void setForcastType(String forcastType) {
        this.forcastType = forcastType == null ? null : forcastType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.predict_time
     *
     * @return the value of forcast_data_view.predict_time
     *
     * @mbggenerated
     */
    public Date getPredictTime() {
        return predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.predict_time
     *
     * @param predictTime the value for forcast_data_view.predict_time
     *
     * @mbggenerated
     */
    public void setPredictTime(Date predictTime) {
        this.predictTime = predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.forcast_time
     *
     * @return the value of forcast_data_view.forcast_time
     *
     * @mbggenerated
     */
    public Date getForcastTime() {
        return forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.forcast_time
     *
     * @param forcastTime the value for forcast_data_view.forcast_time
     *
     * @mbggenerated
     */
    public void setForcastTime(Date forcastTime) {
        this.forcastTime = forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.forcast_day
     *
     * @return the value of forcast_data_view.forcast_day
     *
     * @mbggenerated
     */
    public Integer getForcastDay() {
        return forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.forcast_day
     *
     * @param forcastDay the value for forcast_data_view.forcast_day
     *
     * @mbggenerated
     */
    public void setForcastDay(Integer forcastDay) {
        this.forcastDay = forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.province
     *
     * @return the value of forcast_data_view.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.province
     *
     * @param province the value for forcast_data_view.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.province_code
     *
     * @return the value of forcast_data_view.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.province_code
     *
     * @param provinceCode the value for forcast_data_view.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.city
     *
     * @return the value of forcast_data_view.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.city
     *
     * @param city the value for forcast_data_view.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.city_code
     *
     * @return the value of forcast_data_view.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.city_code
     *
     * @param cityCode the value for forcast_data_view.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.station
     *
     * @return the value of forcast_data_view.station
     *
     * @mbggenerated
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.station
     *
     * @param station the value for forcast_data_view.station
     *
     * @mbggenerated
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.station_code
     *
     * @return the value of forcast_data_view.station_code
     *
     * @mbggenerated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.station_code
     *
     * @param stationCode the value for forcast_data_view.station_code
     *
     * @mbggenerated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.county
     *
     * @return the value of forcast_data_view.county
     *
     * @mbggenerated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.county
     *
     * @param county the value for forcast_data_view.county
     *
     * @mbggenerated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.county_code
     *
     * @return the value of forcast_data_view.county_code
     *
     * @mbggenerated
     */
    public String getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.county_code
     *
     * @param countyCode the value for forcast_data_view.county_code
     *
     * @mbggenerated
     */
    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode == null ? null : countyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.AQI_R
     *
     * @return the value of forcast_data_view.AQI_R
     *
     * @mbggenerated
     */
    public String getaQIR() {
        return aQIR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.AQI_R
     *
     * @param aQIR the value for forcast_data_view.AQI_R
     *
     * @mbggenerated
     */
    public void setaQIR(String aQIR) {
        this.aQIR = aQIR == null ? null : aQIR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.PM2_5_R
     *
     * @return the value of forcast_data_view.PM2_5_R
     *
     * @mbggenerated
     */
    public String getpM25R() {
        return pM25R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.PM2_5_R
     *
     * @param pM25R the value for forcast_data_view.PM2_5_R
     *
     * @mbggenerated
     */
    public void setpM25R(String pM25R) {
        this.pM25R = pM25R == null ? null : pM25R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.PM10_R
     *
     * @return the value of forcast_data_view.PM10_R
     *
     * @mbggenerated
     */
    public String getpM10R() {
        return pM10R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.PM10_R
     *
     * @param pM10R the value for forcast_data_view.PM10_R
     *
     * @mbggenerated
     */
    public void setpM10R(String pM10R) {
        this.pM10R = pM10R == null ? null : pM10R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.SO2_R
     *
     * @return the value of forcast_data_view.SO2_R
     *
     * @mbggenerated
     */
    public String getsO2R() {
        return sO2R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.SO2_R
     *
     * @param sO2R the value for forcast_data_view.SO2_R
     *
     * @mbggenerated
     */
    public void setsO2R(String sO2R) {
        this.sO2R = sO2R == null ? null : sO2R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.NO2_R
     *
     * @return the value of forcast_data_view.NO2_R
     *
     * @mbggenerated
     */
    public String getnO2R() {
        return nO2R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.NO2_R
     *
     * @param nO2R the value for forcast_data_view.NO2_R
     *
     * @mbggenerated
     */
    public void setnO2R(String nO2R) {
        this.nO2R = nO2R == null ? null : nO2R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.CO_R
     *
     * @return the value of forcast_data_view.CO_R
     *
     * @mbggenerated
     */
    public String getcOR() {
        return cOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.CO_R
     *
     * @param cOR the value for forcast_data_view.CO_R
     *
     * @mbggenerated
     */
    public void setcOR(String cOR) {
        this.cOR = cOR == null ? null : cOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.O3_R
     *
     * @return the value of forcast_data_view.O3_R
     *
     * @mbggenerated
     */
    public String getO3R() {
        return o3R;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.O3_R
     *
     * @param o3R the value for forcast_data_view.O3_R
     *
     * @mbggenerated
     */
    public void setO3R(String o3R) {
        this.o3R = o3R == null ? null : o3R.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.RH_R
     *
     * @return the value of forcast_data_view.RH_R
     *
     * @mbggenerated
     */
    public String getrHR() {
        return rHR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.RH_R
     *
     * @param rHR the value for forcast_data_view.RH_R
     *
     * @mbggenerated
     */
    public void setrHR(String rHR) {
        this.rHR = rHR == null ? null : rHR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.Precipitation_R
     *
     * @return the value of forcast_data_view.Precipitation_R
     *
     * @mbggenerated
     */
    public String getPrecipitationR() {
        return precipitationR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.Precipitation_R
     *
     * @param precipitationR the value for forcast_data_view.Precipitation_R
     *
     * @mbggenerated
     */
    public void setPrecipitationR(String precipitationR) {
        this.precipitationR = precipitationR == null ? null : precipitationR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.Temperature_R
     *
     * @return the value of forcast_data_view.Temperature_R
     *
     * @mbggenerated
     */
    public String getTemperatureR() {
        return temperatureR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.Temperature_R
     *
     * @param temperatureR the value for forcast_data_view.Temperature_R
     *
     * @mbggenerated
     */
    public void setTemperatureR(String temperatureR) {
        this.temperatureR = temperatureR == null ? null : temperatureR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.WindSpeed_R
     *
     * @return the value of forcast_data_view.WindSpeed_R
     *
     * @mbggenerated
     */
    public String getWindSpeedR() {
        return windSpeedR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.WindSpeed_R
     *
     * @param windSpeedR the value for forcast_data_view.WindSpeed_R
     *
     * @mbggenerated
     */
    public void setWindSpeedR(String windSpeedR) {
        this.windSpeedR = windSpeedR == null ? null : windSpeedR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.Pressure_R
     *
     * @return the value of forcast_data_view.Pressure_R
     *
     * @mbggenerated
     */
    public String getPressureR() {
        return pressureR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.Pressure_R
     *
     * @param pressureR the value for forcast_data_view.Pressure_R
     *
     * @mbggenerated
     */
    public void setPressureR(String pressureR) {
        this.pressureR = pressureR == null ? null : pressureR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.CloudCover_R
     *
     * @return the value of forcast_data_view.CloudCover_R
     *
     * @mbggenerated
     */
    public String getCloudCoverR() {
        return cloudCoverR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.CloudCover_R
     *
     * @param cloudCoverR the value for forcast_data_view.CloudCover_R
     *
     * @mbggenerated
     */
    public void setCloudCoverR(String cloudCoverR) {
        this.cloudCoverR = cloudCoverR == null ? null : cloudCoverR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.PBL_R
     *
     * @return the value of forcast_data_view.PBL_R
     *
     * @mbggenerated
     */
    public String getpBLR() {
        return pBLR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.PBL_R
     *
     * @param pBLR the value for forcast_data_view.PBL_R
     *
     * @mbggenerated
     */
    public void setpBLR(String pBLR) {
        this.pBLR = pBLR == null ? null : pBLR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.WindDIR_R
     *
     * @return the value of forcast_data_view.WindDIR_R
     *
     * @mbggenerated
     */
    public String getWindDIRR() {
        return windDIRR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.WindDIR_R
     *
     * @param windDIRR the value for forcast_data_view.WindDIR_R
     *
     * @mbggenerated
     */
    public void setWindDIRR(String windDIRR) {
        this.windDIRR = windDIRR == null ? null : windDIRR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.AQI_C
     *
     * @return the value of forcast_data_view.AQI_C
     *
     * @mbggenerated
     */
    public String getaQIC() {
        return aQIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.AQI_C
     *
     * @param aQIC the value for forcast_data_view.AQI_C
     *
     * @mbggenerated
     */
    public void setaQIC(String aQIC) {
        this.aQIC = aQIC == null ? null : aQIC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.PM2_5_C
     *
     * @return the value of forcast_data_view.PM2_5_C
     *
     * @mbggenerated
     */
    public String getpM25C() {
        return pM25C;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.PM2_5_C
     *
     * @param pM25C the value for forcast_data_view.PM2_5_C
     *
     * @mbggenerated
     */
    public void setpM25C(String pM25C) {
        this.pM25C = pM25C == null ? null : pM25C.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.PM10_C
     *
     * @return the value of forcast_data_view.PM10_C
     *
     * @mbggenerated
     */
    public String getpM10C() {
        return pM10C;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.PM10_C
     *
     * @param pM10C the value for forcast_data_view.PM10_C
     *
     * @mbggenerated
     */
    public void setpM10C(String pM10C) {
        this.pM10C = pM10C == null ? null : pM10C.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.SO2_C
     *
     * @return the value of forcast_data_view.SO2_C
     *
     * @mbggenerated
     */
    public String getsO2C() {
        return sO2C;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.SO2_C
     *
     * @param sO2C the value for forcast_data_view.SO2_C
     *
     * @mbggenerated
     */
    public void setsO2C(String sO2C) {
        this.sO2C = sO2C == null ? null : sO2C.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.NO2_C
     *
     * @return the value of forcast_data_view.NO2_C
     *
     * @mbggenerated
     */
    public String getnO2C() {
        return nO2C;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.NO2_C
     *
     * @param nO2C the value for forcast_data_view.NO2_C
     *
     * @mbggenerated
     */
    public void setnO2C(String nO2C) {
        this.nO2C = nO2C == null ? null : nO2C.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.CO_C
     *
     * @return the value of forcast_data_view.CO_C
     *
     * @mbggenerated
     */
    public String getcOC() {
        return cOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.CO_C
     *
     * @param cOC the value for forcast_data_view.CO_C
     *
     * @mbggenerated
     */
    public void setcOC(String cOC) {
        this.cOC = cOC == null ? null : cOC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.O3_C
     *
     * @return the value of forcast_data_view.O3_C
     *
     * @mbggenerated
     */
    public String getO3C() {
        return o3C;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.O3_C
     *
     * @param o3C the value for forcast_data_view.O3_C
     *
     * @mbggenerated
     */
    public void setO3C(String o3C) {
        this.o3C = o3C == null ? null : o3C.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.RH_C
     *
     * @return the value of forcast_data_view.RH_C
     *
     * @mbggenerated
     */
    public String getrHC() {
        return rHC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.RH_C
     *
     * @param rHC the value for forcast_data_view.RH_C
     *
     * @mbggenerated
     */
    public void setrHC(String rHC) {
        this.rHC = rHC == null ? null : rHC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.Precipitation_C
     *
     * @return the value of forcast_data_view.Precipitation_C
     *
     * @mbggenerated
     */
    public String getPrecipitationC() {
        return precipitationC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.Precipitation_C
     *
     * @param precipitationC the value for forcast_data_view.Precipitation_C
     *
     * @mbggenerated
     */
    public void setPrecipitationC(String precipitationC) {
        this.precipitationC = precipitationC == null ? null : precipitationC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.Temperature_C
     *
     * @return the value of forcast_data_view.Temperature_C
     *
     * @mbggenerated
     */
    public String getTemperatureC() {
        return temperatureC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.Temperature_C
     *
     * @param temperatureC the value for forcast_data_view.Temperature_C
     *
     * @mbggenerated
     */
    public void setTemperatureC(String temperatureC) {
        this.temperatureC = temperatureC == null ? null : temperatureC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.WindSpeed_C
     *
     * @return the value of forcast_data_view.WindSpeed_C
     *
     * @mbggenerated
     */
    public String getWindSpeedC() {
        return windSpeedC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.WindSpeed_C
     *
     * @param windSpeedC the value for forcast_data_view.WindSpeed_C
     *
     * @mbggenerated
     */
    public void setWindSpeedC(String windSpeedC) {
        this.windSpeedC = windSpeedC == null ? null : windSpeedC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.Pressure_C
     *
     * @return the value of forcast_data_view.Pressure_C
     *
     * @mbggenerated
     */
    public String getPressureC() {
        return pressureC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.Pressure_C
     *
     * @param pressureC the value for forcast_data_view.Pressure_C
     *
     * @mbggenerated
     */
    public void setPressureC(String pressureC) {
        this.pressureC = pressureC == null ? null : pressureC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.CloudCover_C
     *
     * @return the value of forcast_data_view.CloudCover_C
     *
     * @mbggenerated
     */
    public String getCloudCoverC() {
        return cloudCoverC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.CloudCover_C
     *
     * @param cloudCoverC the value for forcast_data_view.CloudCover_C
     *
     * @mbggenerated
     */
    public void setCloudCoverC(String cloudCoverC) {
        this.cloudCoverC = cloudCoverC == null ? null : cloudCoverC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.PBL_C
     *
     * @return the value of forcast_data_view.PBL_C
     *
     * @mbggenerated
     */
    public String getpBLC() {
        return pBLC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.PBL_C
     *
     * @param pBLC the value for forcast_data_view.PBL_C
     *
     * @mbggenerated
     */
    public void setpBLC(String pBLC) {
        this.pBLC = pBLC == null ? null : pBLC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.WindDIR_C
     *
     * @return the value of forcast_data_view.WindDIR_C
     *
     * @mbggenerated
     */
    public String getWindDIRC() {
        return windDIRC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.WindDIR_C
     *
     * @param windDIRC the value for forcast_data_view.WindDIR_C
     *
     * @mbggenerated
     */
    public void setWindDIRC(String windDIRC) {
        this.windDIRC = windDIRC == null ? null : windDIRC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.AQI_O
     *
     * @return the value of forcast_data_view.AQI_O
     *
     * @mbggenerated
     */
    public String getaQIO() {
        return aQIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.AQI_O
     *
     * @param aQIO the value for forcast_data_view.AQI_O
     *
     * @mbggenerated
     */
    public void setaQIO(String aQIO) {
        this.aQIO = aQIO == null ? null : aQIO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.PM2_5_O
     *
     * @return the value of forcast_data_view.PM2_5_O
     *
     * @mbggenerated
     */
    public String getpM25O() {
        return pM25O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.PM2_5_O
     *
     * @param pM25O the value for forcast_data_view.PM2_5_O
     *
     * @mbggenerated
     */
    public void setpM25O(String pM25O) {
        this.pM25O = pM25O == null ? null : pM25O.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.PM10_O
     *
     * @return the value of forcast_data_view.PM10_O
     *
     * @mbggenerated
     */
    public String getpM10O() {
        return pM10O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.PM10_O
     *
     * @param pM10O the value for forcast_data_view.PM10_O
     *
     * @mbggenerated
     */
    public void setpM10O(String pM10O) {
        this.pM10O = pM10O == null ? null : pM10O.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.SO2_O
     *
     * @return the value of forcast_data_view.SO2_O
     *
     * @mbggenerated
     */
    public String getsO2O() {
        return sO2O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.SO2_O
     *
     * @param sO2O the value for forcast_data_view.SO2_O
     *
     * @mbggenerated
     */
    public void setsO2O(String sO2O) {
        this.sO2O = sO2O == null ? null : sO2O.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.NO2_O
     *
     * @return the value of forcast_data_view.NO2_O
     *
     * @mbggenerated
     */
    public String getnO2O() {
        return nO2O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.NO2_O
     *
     * @param nO2O the value for forcast_data_view.NO2_O
     *
     * @mbggenerated
     */
    public void setnO2O(String nO2O) {
        this.nO2O = nO2O == null ? null : nO2O.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.CO_O
     *
     * @return the value of forcast_data_view.CO_O
     *
     * @mbggenerated
     */
    public String getcOO() {
        return cOO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.CO_O
     *
     * @param cOO the value for forcast_data_view.CO_O
     *
     * @mbggenerated
     */
    public void setcOO(String cOO) {
        this.cOO = cOO == null ? null : cOO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.O3_O
     *
     * @return the value of forcast_data_view.O3_O
     *
     * @mbggenerated
     */
    public String getO3O() {
        return o3O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.O3_O
     *
     * @param o3O the value for forcast_data_view.O3_O
     *
     * @mbggenerated
     */
    public void setO3O(String o3O) {
        this.o3O = o3O == null ? null : o3O.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.RH_O
     *
     * @return the value of forcast_data_view.RH_O
     *
     * @mbggenerated
     */
    public String getrHO() {
        return rHO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.RH_O
     *
     * @param rHO the value for forcast_data_view.RH_O
     *
     * @mbggenerated
     */
    public void setrHO(String rHO) {
        this.rHO = rHO == null ? null : rHO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.Precipitation_O
     *
     * @return the value of forcast_data_view.Precipitation_O
     *
     * @mbggenerated
     */
    public String getPrecipitationO() {
        return precipitationO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.Precipitation_O
     *
     * @param precipitationO the value for forcast_data_view.Precipitation_O
     *
     * @mbggenerated
     */
    public void setPrecipitationO(String precipitationO) {
        this.precipitationO = precipitationO == null ? null : precipitationO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.Temperature_O
     *
     * @return the value of forcast_data_view.Temperature_O
     *
     * @mbggenerated
     */
    public String getTemperatureO() {
        return temperatureO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.Temperature_O
     *
     * @param temperatureO the value for forcast_data_view.Temperature_O
     *
     * @mbggenerated
     */
    public void setTemperatureO(String temperatureO) {
        this.temperatureO = temperatureO == null ? null : temperatureO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.WindSpeed_O
     *
     * @return the value of forcast_data_view.WindSpeed_O
     *
     * @mbggenerated
     */
    public String getWindSpeedO() {
        return windSpeedO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.WindSpeed_O
     *
     * @param windSpeedO the value for forcast_data_view.WindSpeed_O
     *
     * @mbggenerated
     */
    public void setWindSpeedO(String windSpeedO) {
        this.windSpeedO = windSpeedO == null ? null : windSpeedO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.Pressure_O
     *
     * @return the value of forcast_data_view.Pressure_O
     *
     * @mbggenerated
     */
    public String getPressureO() {
        return pressureO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.Pressure_O
     *
     * @param pressureO the value for forcast_data_view.Pressure_O
     *
     * @mbggenerated
     */
    public void setPressureO(String pressureO) {
        this.pressureO = pressureO == null ? null : pressureO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.CloudCover_O
     *
     * @return the value of forcast_data_view.CloudCover_O
     *
     * @mbggenerated
     */
    public String getCloudCoverO() {
        return cloudCoverO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.CloudCover_O
     *
     * @param cloudCoverO the value for forcast_data_view.CloudCover_O
     *
     * @mbggenerated
     */
    public void setCloudCoverO(String cloudCoverO) {
        this.cloudCoverO = cloudCoverO == null ? null : cloudCoverO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.PBL_O
     *
     * @return the value of forcast_data_view.PBL_O
     *
     * @mbggenerated
     */
    public String getpBLO() {
        return pBLO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.PBL_O
     *
     * @param pBLO the value for forcast_data_view.PBL_O
     *
     * @mbggenerated
     */
    public void setpBLO(String pBLO) {
        this.pBLO = pBLO == null ? null : pBLO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forcast_data_view.WindDIR_O
     *
     * @return the value of forcast_data_view.WindDIR_O
     *
     * @mbggenerated
     */
    public String getWindDIRO() {
        return windDIRO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forcast_data_view.WindDIR_O
     *
     * @param windDIRO the value for forcast_data_view.WindDIR_O
     *
     * @mbggenerated
     */
    public void setWindDIRO(String windDIRO) {
        this.windDIRO = windDIRO == null ? null : windDIRO.trim();
    }
}