package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto.vo.SelectVO;

import java.util.Date;

public class ForecastAudit extends SelectVO {
	private static final long serialVersionUID = 1L;

    private String pm25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.timepoint
     *
     * @mbggenerated
     */
    private Date timepoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.citycode
     *
     * @mbggenerated
     */
    private Integer citycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.timepoint
     *
     * @return the value of forecastAudit.timepoint
     *
     * @mbggenerated
     */
    public Date getTimepoint() {
        return timepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.timepoint
     *
     * @param timepoint the value for forecastAudit.timepoint
     *
     * @mbggenerated
     */
    public void setTimepoint(Date timepoint) {
        this.timepoint = timepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.citycode
     *
     * @return the value of forecastAudit.citycode
     *
     * @mbggenerated
     */
    public Integer getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.citycode
     *
     * @param citycode the value for forecastAudit.citycode
     *
     * @mbggenerated
     */
    public void setCitycode(Integer citycode) {
        this.citycode = citycode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.ID
     *
     * @mbggenerated
     */
    private Integer iD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.aqi
     *
     * @mbggenerated
     */
    private String aqi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.PrimaryPollutant
     *
     * @mbggenerated
     */
    private String primaryPollutant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.quality
     *
     * @mbggenerated
     */
    private String quality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.aqiContent
     *
     * @mbggenerated
     */
    private String aqiContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.PrimaryPollutantContent
     *
     * @mbggenerated
     */
    private String primaryPollutantContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastAudit.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.ID
     *
     * @return the value of forecastAudit.ID
     *
     * @mbggenerated
     */
    public Integer getiD() {
        return iD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.ID
     *
     * @param iD the value for forecastAudit.ID
     *
     * @mbggenerated
     */
    public void setiD(Integer iD) {
        this.iD = iD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.username
     *
     * @return the value of forecastAudit.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.username
     *
     * @param username the value for forecastAudit.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.userid
     *
     * @return the value of forecastAudit.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.userid
     *
     * @param userid the value for forecastAudit.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.content
     *
     * @return the value of forecastAudit.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.content
     *
     * @param content the value for forecastAudit.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.aqi
     *
     * @return the value of forecastAudit.aqi
     *
     * @mbggenerated
     */
    public String getAqi() {
        return aqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.aqi
     *
     * @param aqi the value for forecastAudit.aqi
     *
     * @mbggenerated
     */
    public void setAqi(String aqi) {
        this.aqi = aqi == null ? null : aqi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.PrimaryPollutant
     *
     * @return the value of forecastAudit.PrimaryPollutant
     *
     * @mbggenerated
     */
    public String getPrimaryPollutant() {
        return primaryPollutant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.PrimaryPollutant
     *
     * @param primaryPollutant the value for forecastAudit.PrimaryPollutant
     *
     * @mbggenerated
     */
    public void setPrimaryPollutant(String primaryPollutant) {
        this.primaryPollutant = primaryPollutant == null ? null : primaryPollutant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.quality
     *
     * @return the value of forecastAudit.quality
     *
     * @mbggenerated
     */
    public String getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.quality
     *
     * @param quality the value for forecastAudit.quality
     *
     * @mbggenerated
     */
    public void setQuality(String quality) {
        this.quality = quality == null ? null : quality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.aqiContent
     *
     * @return the value of forecastAudit.aqiContent
     *
     * @mbggenerated
     */
    public String getAqiContent() {
        return aqiContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.aqiContent
     *
     * @param aqiContent the value for forecastAudit.aqiContent
     *
     * @mbggenerated
     */
    public void setAqiContent(String aqiContent) {
        this.aqiContent = aqiContent == null ? null : aqiContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.PrimaryPollutantContent
     *
     * @return the value of forecastAudit.PrimaryPollutantContent
     *
     * @mbggenerated
     */
    public String getPrimaryPollutantContent() {
        return primaryPollutantContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.PrimaryPollutantContent
     *
     * @param primaryPollutantContent the value for forecastAudit.PrimaryPollutantContent
     *
     * @mbggenerated
     */
    public void setPrimaryPollutantContent(String primaryPollutantContent) {
        this.primaryPollutantContent = primaryPollutantContent == null ? null : primaryPollutantContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastAudit.message
     *
     * @return the value of forecastAudit.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastAudit.message
     *
     * @param message the value for forecastAudit.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    public String getPm25() {
        return pm25;
    }

    public void setPm25(String pm25) {
        this.pm25 = pm25;
    }
}