package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto.vo.SelectVO;

import java.util.Date;

public class ForecastSet extends SelectVO{
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.ID
     *
     * @mbggenerated
     */
    private Integer iD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.timepoint
     *
     * @mbggenerated
     */
    private Date timepoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.citycode
     *
     * @mbggenerated
     */
    private Integer citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.pm2_5
     *
     * @mbggenerated
     */
    private String pm25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.pm2_5_dr
     *
     * @mbggenerated
     */
    private String pm25Dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.pm2_5_ir
     *
     * @mbggenerated
     */
    private String pm25Ir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.o3
     *
     * @mbggenerated
     */
    private String o3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.o3_dr
     *
     * @mbggenerated
     */
    private String o3Dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.o3_ir
     *
     * @mbggenerated
     */
    private String o3Ir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.aqi
     *
     * @mbggenerated
     */
    private String aqi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.aqi_po
     *
     * @mbggenerated
     */
    private String aqiPo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.aqi_npo
     *
     * @mbggenerated
     */
    private String aqiNpo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.aqiContent
     *
     * @mbggenerated
     */
    private String aqiContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecastSet.pm2_5IAQI
     *
     * @mbggenerated
     */
    private String pm25IAQI;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.ID
     *
     * @return the value of forecastSet.ID
     *
     * @mbggenerated
     */
    public Integer getiD() {
        return iD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.ID
     *
     * @param iD the value for forecastSet.ID
     *
     * @mbggenerated
     */
    public void setiD(Integer iD) {
        this.iD = iD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.timepoint
     *
     * @return the value of forecastSet.timepoint
     *
     * @mbggenerated
     */
    public Date getTimepoint() {
        return timepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.timepoint
     *
     * @param timepoint the value for forecastSet.timepoint
     *
     * @mbggenerated
     */
    public void setTimepoint(Date timepoint) {
        this.timepoint = timepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.citycode
     *
     * @return the value of forecastSet.citycode
     *
     * @mbggenerated
     */
    public Integer getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.citycode
     *
     * @param citycode the value for forecastSet.citycode
     *
     * @mbggenerated
     */
    public void setCitycode(Integer citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.type
     *
     * @return the value of forecastSet.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.type
     *
     * @param type the value for forecastSet.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.name
     *
     * @return the value of forecastSet.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.name
     *
     * @param name the value for forecastSet.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.pm2_5
     *
     * @return the value of forecastSet.pm2_5
     *
     * @mbggenerated
     */
    public String getPm25() {
        return pm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.pm2_5
     *
     * @param pm25 the value for forecastSet.pm2_5
     *
     * @mbggenerated
     */
    public void setPm25(String pm25) {
        this.pm25 = pm25 == null ? null : pm25.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.pm2_5_dr
     *
     * @return the value of forecastSet.pm2_5_dr
     *
     * @mbggenerated
     */
    public String getPm25Dr() {
        return pm25Dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.pm2_5_dr
     *
     * @param pm25Dr the value for forecastSet.pm2_5_dr
     *
     * @mbggenerated
     */
    public void setPm25Dr(String pm25Dr) {
        this.pm25Dr = pm25Dr == null ? null : pm25Dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.pm2_5_ir
     *
     * @return the value of forecastSet.pm2_5_ir
     *
     * @mbggenerated
     */
    public String getPm25Ir() {
        return pm25Ir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.pm2_5_ir
     *
     * @param pm25Ir the value for forecastSet.pm2_5_ir
     *
     * @mbggenerated
     */
    public void setPm25Ir(String pm25Ir) {
        this.pm25Ir = pm25Ir == null ? null : pm25Ir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.o3
     *
     * @return the value of forecastSet.o3
     *
     * @mbggenerated
     */
    public String getO3() {
        return o3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.o3
     *
     * @param o3 the value for forecastSet.o3
     *
     * @mbggenerated
     */
    public void setO3(String o3) {
        this.o3 = o3 == null ? null : o3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.o3_dr
     *
     * @return the value of forecastSet.o3_dr
     *
     * @mbggenerated
     */
    public String getO3Dr() {
        return o3Dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.o3_dr
     *
     * @param o3Dr the value for forecastSet.o3_dr
     *
     * @mbggenerated
     */
    public void setO3Dr(String o3Dr) {
        this.o3Dr = o3Dr == null ? null : o3Dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.o3_ir
     *
     * @return the value of forecastSet.o3_ir
     *
     * @mbggenerated
     */
    public String getO3Ir() {
        return o3Ir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.o3_ir
     *
     * @param o3Ir the value for forecastSet.o3_ir
     *
     * @mbggenerated
     */
    public void setO3Ir(String o3Ir) {
        this.o3Ir = o3Ir == null ? null : o3Ir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.aqi
     *
     * @return the value of forecastSet.aqi
     *
     * @mbggenerated
     */
    public String getAqi() {
        return aqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.aqi
     *
     * @param aqi the value for forecastSet.aqi
     *
     * @mbggenerated
     */
    public void setAqi(String aqi) {
        this.aqi = aqi == null ? null : aqi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.aqi_po
     *
     * @return the value of forecastSet.aqi_po
     *
     * @mbggenerated
     */
    public String getAqiPo() {
        return aqiPo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.aqi_po
     *
     * @param aqiPo the value for forecastSet.aqi_po
     *
     * @mbggenerated
     */
    public void setAqiPo(String aqiPo) {
        this.aqiPo = aqiPo == null ? null : aqiPo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.aqi_npo
     *
     * @return the value of forecastSet.aqi_npo
     *
     * @mbggenerated
     */
    public String getAqiNpo() {
        return aqiNpo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.aqi_npo
     *
     * @param aqiNpo the value for forecastSet.aqi_npo
     *
     * @mbggenerated
     */
    public void setAqiNpo(String aqiNpo) {
        this.aqiNpo = aqiNpo == null ? null : aqiNpo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.aqiContent
     *
     * @return the value of forecastSet.aqiContent
     *
     * @mbggenerated
     */
    public String getAqiContent() {
        return aqiContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.aqiContent
     *
     * @param aqiContent the value for forecastSet.aqiContent
     *
     * @mbggenerated
     */
    public void setAqiContent(String aqiContent) {
        this.aqiContent = aqiContent == null ? null : aqiContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecastSet.pm2_5IAQI
     *
     * @return the value of forecastSet.pm2_5IAQI
     *
     * @mbggenerated
     */
    public String getPm25IAQI() {
        return pm25IAQI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecastSet.pm2_5IAQI
     *
     * @param pm25IAQI the value for forecastSet.pm2_5IAQI
     *
     * @mbggenerated
     */
    public void setPm25IAQI(String pm25IAQI) {
        this.pm25IAQI = pm25IAQI == null ? null : pm25IAQI.trim();
    }
}