package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class GWFactCityHour {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.ID
     *
     * @mbggenerated
     */
    private Integer iD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.datetime
     *
     * @mbggenerated
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.citycode
     *
     * @mbggenerated
     */
    private Integer citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.cityname
     *
     * @mbggenerated
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.stationcount
     *
     * @mbggenerated
     */
    private Integer stationcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.SO2
     *
     * @mbggenerated
     */
    private String sO2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.NO2
     *
     * @mbggenerated
     */
    private String nO2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.PM10
     *
     * @mbggenerated
     */
    private String pM10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.CO
     *
     * @mbggenerated
     */
    private String cO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.O3
     *
     * @mbggenerated
     */
    private String o3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.PM25
     *
     * @mbggenerated
     */
    private String pM25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.Chiefly_Infectant
     *
     * @mbggenerated
     */
    private String chieflyInfectant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.Grade
     *
     * @mbggenerated
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.GradeDescription
     *
     * @mbggenerated
     */
    private String gradeDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.AQI
     *
     * @mbggenerated
     */
    private String aQI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.Color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GW_Fact_CityHour.inputdate
     *
     * @mbggenerated
     */
    private Date inputdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.ID
     *
     * @return the value of GW_Fact_CityHour.ID
     *
     * @mbggenerated
     */
    public Integer getiD() {
        return iD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.ID
     *
     * @param iD the value for GW_Fact_CityHour.ID
     *
     * @mbggenerated
     */
    public void setiD(Integer iD) {
        this.iD = iD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.datetime
     *
     * @return the value of GW_Fact_CityHour.datetime
     *
     * @mbggenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.datetime
     *
     * @param datetime the value for GW_Fact_CityHour.datetime
     *
     * @mbggenerated
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.citycode
     *
     * @return the value of GW_Fact_CityHour.citycode
     *
     * @mbggenerated
     */
    public Integer getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.citycode
     *
     * @param citycode the value for GW_Fact_CityHour.citycode
     *
     * @mbggenerated
     */
    public void setCitycode(Integer citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.cityname
     *
     * @return the value of GW_Fact_CityHour.cityname
     *
     * @mbggenerated
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.cityname
     *
     * @param cityname the value for GW_Fact_CityHour.cityname
     *
     * @mbggenerated
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.stationcount
     *
     * @return the value of GW_Fact_CityHour.stationcount
     *
     * @mbggenerated
     */
    public Integer getStationcount() {
        return stationcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.stationcount
     *
     * @param stationcount the value for GW_Fact_CityHour.stationcount
     *
     * @mbggenerated
     */
    public void setStationcount(Integer stationcount) {
        this.stationcount = stationcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.SO2
     *
     * @return the value of GW_Fact_CityHour.SO2
     *
     * @mbggenerated
     */
    public String getsO2() {
        return sO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.SO2
     *
     * @param sO2 the value for GW_Fact_CityHour.SO2
     *
     * @mbggenerated
     */
    public void setsO2(String sO2) {
        this.sO2 = sO2 == null ? null : sO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.NO2
     *
     * @return the value of GW_Fact_CityHour.NO2
     *
     * @mbggenerated
     */
    public String getnO2() {
        return nO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.NO2
     *
     * @param nO2 the value for GW_Fact_CityHour.NO2
     *
     * @mbggenerated
     */
    public void setnO2(String nO2) {
        this.nO2 = nO2 == null ? null : nO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.PM10
     *
     * @return the value of GW_Fact_CityHour.PM10
     *
     * @mbggenerated
     */
    public String getpM10() {
        return pM10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.PM10
     *
     * @param pM10 the value for GW_Fact_CityHour.PM10
     *
     * @mbggenerated
     */
    public void setpM10(String pM10) {
        this.pM10 = pM10 == null ? null : pM10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.CO
     *
     * @return the value of GW_Fact_CityHour.CO
     *
     * @mbggenerated
     */
    public String getcO() {
        return cO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.CO
     *
     * @param cO the value for GW_Fact_CityHour.CO
     *
     * @mbggenerated
     */
    public void setcO(String cO) {
        this.cO = cO == null ? null : cO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.O3
     *
     * @return the value of GW_Fact_CityHour.O3
     *
     * @mbggenerated
     */
    public String getO3() {
        return o3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.O3
     *
     * @param o3 the value for GW_Fact_CityHour.O3
     *
     * @mbggenerated
     */
    public void setO3(String o3) {
        this.o3 = o3 == null ? null : o3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.PM25
     *
     * @return the value of GW_Fact_CityHour.PM25
     *
     * @mbggenerated
     */
    public String getpM25() {
        return pM25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.PM25
     *
     * @param pM25 the value for GW_Fact_CityHour.PM25
     *
     * @mbggenerated
     */
    public void setpM25(String pM25) {
        this.pM25 = pM25 == null ? null : pM25.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.Chiefly_Infectant
     *
     * @return the value of GW_Fact_CityHour.Chiefly_Infectant
     *
     * @mbggenerated
     */
    public String getChieflyInfectant() {
        return chieflyInfectant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.Chiefly_Infectant
     *
     * @param chieflyInfectant the value for GW_Fact_CityHour.Chiefly_Infectant
     *
     * @mbggenerated
     */
    public void setChieflyInfectant(String chieflyInfectant) {
        this.chieflyInfectant = chieflyInfectant == null ? null : chieflyInfectant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.Grade
     *
     * @return the value of GW_Fact_CityHour.Grade
     *
     * @mbggenerated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.Grade
     *
     * @param grade the value for GW_Fact_CityHour.Grade
     *
     * @mbggenerated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.GradeDescription
     *
     * @return the value of GW_Fact_CityHour.GradeDescription
     *
     * @mbggenerated
     */
    public String getGradeDescription() {
        return gradeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.GradeDescription
     *
     * @param gradeDescription the value for GW_Fact_CityHour.GradeDescription
     *
     * @mbggenerated
     */
    public void setGradeDescription(String gradeDescription) {
        this.gradeDescription = gradeDescription == null ? null : gradeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.AQI
     *
     * @return the value of GW_Fact_CityHour.AQI
     *
     * @mbggenerated
     */
    public String getaQI() {
        return aQI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.AQI
     *
     * @param aQI the value for GW_Fact_CityHour.AQI
     *
     * @mbggenerated
     */
    public void setaQI(String aQI) {
        this.aQI = aQI == null ? null : aQI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.Color
     *
     * @return the value of GW_Fact_CityHour.Color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.Color
     *
     * @param color the value for GW_Fact_CityHour.Color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GW_Fact_CityHour.inputdate
     *
     * @return the value of GW_Fact_CityHour.inputdate
     *
     * @mbggenerated
     */
    public Date getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GW_Fact_CityHour.inputdate
     *
     * @param inputdate the value for GW_Fact_CityHour.inputdate
     *
     * @mbggenerated
     */
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }
}