package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class MediumLongAnalysisPollutant {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.report_time
     *
     * @mbggenerated
     */
    private Date reportTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.PM2_5
     *
     * @mbggenerated
     */
    private String pM25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.O3_8h
     *
     * @mbggenerated
     */
    private String o38h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.SO2
     *
     * @mbggenerated
     */
    private String sO2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.NO2
     *
     * @mbggenerated
     */
    private String nO2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.CO
     *
     * @mbggenerated
     */
    private String cO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.PM_10
     *
     * @mbggenerated
     */
    private String pM10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_pollutant.IS_NONE
     *
     * @mbggenerated
     */
    private String iSNONE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.id
     *
     * @return the value of medium_long_analysis_pollutant.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.id
     *
     * @param id the value for medium_long_analysis_pollutant.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.city
     *
     * @return the value of medium_long_analysis_pollutant.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.city
     *
     * @param city the value for medium_long_analysis_pollutant.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.city_code
     *
     * @return the value of medium_long_analysis_pollutant.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.city_code
     *
     * @param cityCode the value for medium_long_analysis_pollutant.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.report_time
     *
     * @return the value of medium_long_analysis_pollutant.report_time
     *
     * @mbggenerated
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.report_time
     *
     * @param reportTime the value for medium_long_analysis_pollutant.report_time
     *
     * @mbggenerated
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.PM2_5
     *
     * @return the value of medium_long_analysis_pollutant.PM2_5
     *
     * @mbggenerated
     */
    public String getpM25() {
        return pM25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.PM2_5
     *
     * @param pM25 the value for medium_long_analysis_pollutant.PM2_5
     *
     * @mbggenerated
     */
    public void setpM25(String pM25) {
        this.pM25 = pM25 == null ? null : pM25.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.O3_8h
     *
     * @return the value of medium_long_analysis_pollutant.O3_8h
     *
     * @mbggenerated
     */
    public String getO38h() {
        return o38h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.O3_8h
     *
     * @param o38h the value for medium_long_analysis_pollutant.O3_8h
     *
     * @mbggenerated
     */
    public void setO38h(String o38h) {
        this.o38h = o38h == null ? null : o38h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.SO2
     *
     * @return the value of medium_long_analysis_pollutant.SO2
     *
     * @mbggenerated
     */
    public String getsO2() {
        return sO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.SO2
     *
     * @param sO2 the value for medium_long_analysis_pollutant.SO2
     *
     * @mbggenerated
     */
    public void setsO2(String sO2) {
        this.sO2 = sO2 == null ? null : sO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.NO2
     *
     * @return the value of medium_long_analysis_pollutant.NO2
     *
     * @mbggenerated
     */
    public String getnO2() {
        return nO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.NO2
     *
     * @param nO2 the value for medium_long_analysis_pollutant.NO2
     *
     * @mbggenerated
     */
    public void setnO2(String nO2) {
        this.nO2 = nO2 == null ? null : nO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.CO
     *
     * @return the value of medium_long_analysis_pollutant.CO
     *
     * @mbggenerated
     */
    public String getcO() {
        return cO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.CO
     *
     * @param cO the value for medium_long_analysis_pollutant.CO
     *
     * @mbggenerated
     */
    public void setcO(String cO) {
        this.cO = cO == null ? null : cO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.PM_10
     *
     * @return the value of medium_long_analysis_pollutant.PM_10
     *
     * @mbggenerated
     */
    public String getpM10() {
        return pM10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.PM_10
     *
     * @param pM10 the value for medium_long_analysis_pollutant.PM_10
     *
     * @mbggenerated
     */
    public void setpM10(String pM10) {
        this.pM10 = pM10 == null ? null : pM10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_pollutant.IS_NONE
     *
     * @return the value of medium_long_analysis_pollutant.IS_NONE
     *
     * @mbggenerated
     */
    public String getiSNONE() {
        return iSNONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_pollutant.IS_NONE
     *
     * @param iSNONE the value for medium_long_analysis_pollutant.IS_NONE
     *
     * @mbggenerated
     */
    public void setiSNONE(String iSNONE) {
        this.iSNONE = iSNONE == null ? null : iSNONE.trim();
    }
}