package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class MediumLongAnalysisParam {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_param.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_param.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_param.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_param.report_time
     *
     * @mbggenerated
     */
    private Date reportTime;
    private Date forcastTime;

    public Date getForcastTime() {
        return forcastTime;
    }

    public void setForcastTime(Date forcastTime) {
        this.forcastTime = forcastTime;
    }

    public String getParamValueL() {
        return paramValueL;
    }

    public void setParamValueL(String paramValueL) {
        this.paramValueL = paramValueL;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_param.param
     *
     * @mbggenerated
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_param.param_value
     *
     * @mbggenerated
     */
    private String paramValue;
    private String paramValueL;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_param.id
     *
     * @return the value of medium_long_analysis_param.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_param.id
     *
     * @param id the value for medium_long_analysis_param.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_param.city
     *
     * @return the value of medium_long_analysis_param.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_param.city
     *
     * @param city the value for medium_long_analysis_param.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_param.city_code
     *
     * @return the value of medium_long_analysis_param.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_param.city_code
     *
     * @param cityCode the value for medium_long_analysis_param.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_param.report_time
     *
     * @return the value of medium_long_analysis_param.report_time
     *
     * @mbggenerated
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_param.report_time
     *
     * @param reportTime the value for medium_long_analysis_param.report_time
     *
     * @mbggenerated
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_param.param
     *
     * @return the value of medium_long_analysis_param.param
     *
     * @mbggenerated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_param.param
     *
     * @param param the value for medium_long_analysis_param.param
     *
     * @mbggenerated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_param.param_value
     *
     * @return the value of medium_long_analysis_param.param_value
     *
     * @mbggenerated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_param.param_value
     *
     * @param paramValue the value for medium_long_analysis_param.param_value
     *
     * @mbggenerated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }
}