package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class MediumLongAnalysisAir {
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_air.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_air.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_air.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_air.report_time
     *
     * @mbggenerated
     */
    private Date reportTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_air.lvl_name
     *
     * @mbggenerated
     */
    private String lvlName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medium_long_analysis_air.lvl_code
     *
     * @mbggenerated
     */
    private String lvlCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_air.id
     *
     * @return the value of medium_long_analysis_air.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_air.id
     *
     * @param id the value for medium_long_analysis_air.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_air.city
     *
     * @return the value of medium_long_analysis_air.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_air.city
     *
     * @param city the value for medium_long_analysis_air.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_air.city_code
     *
     * @return the value of medium_long_analysis_air.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_air.city_code
     *
     * @param cityCode the value for medium_long_analysis_air.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_air.report_time
     *
     * @return the value of medium_long_analysis_air.report_time
     *
     * @mbggenerated
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_air.report_time
     *
     * @param reportTime the value for medium_long_analysis_air.report_time
     *
     * @mbggenerated
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_air.lvl_name
     *
     * @return the value of medium_long_analysis_air.lvl_name
     *
     * @mbggenerated
     */
    public String getLvlName() {
        return lvlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_air.lvl_name
     *
     * @param lvlName the value for medium_long_analysis_air.lvl_name
     *
     * @mbggenerated
     */
    public void setLvlName(String lvlName) {
        this.lvlName = lvlName == null ? null : lvlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medium_long_analysis_air.lvl_code
     *
     * @return the value of medium_long_analysis_air.lvl_code
     *
     * @mbggenerated
     */
    public String getLvlCode() {
        return lvlCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medium_long_analysis_air.lvl_code
     *
     * @param lvlCode the value for medium_long_analysis_air.lvl_code
     *
     * @mbggenerated
     */
    public void setLvlCode(String lvlCode) {
        this.lvlCode = lvlCode == null ? null : lvlCode.trim();
    }
}