package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class PollutantAnalysis {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutant_analysis2.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutant_analysis2.city
     *
     * @mbggenerated
     */
    private String city;
    private String stationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutant_analysis2.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutant_analysis2.predict_time
     *
     * @mbggenerated
     */
    private Date predictTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutant_analysis2.forcast_time
     *
     * @mbggenerated
     */
    private Date forcastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutant_analysis2.forcast_day
     *
     * @mbggenerated
     */
    private Integer forcastDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutant_analysis2.pollutant_group
     *
     * @mbggenerated
     */
    private String pollutantGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutant_analysis2.pollutant_name
     *
     * @mbggenerated
     */
    private String pollutantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pollutant_analysis2.pollutant_value
     *
     * @mbggenerated
     */
    private String pollutantValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutant_analysis2.id
     *
     * @return the value of pollutant_analysis2.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pollutant_analysis2.id
     *
     * @param id the value for pollutant_analysis2.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutant_analysis2.city
     *
     * @return the value of pollutant_analysis2.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pollutant_analysis2.city
     *
     * @param city the value for pollutant_analysis2.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutant_analysis2.city_code
     *
     * @return the value of pollutant_analysis2.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pollutant_analysis2.city_code
     *
     * @param cityCode the value for pollutant_analysis2.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutant_analysis2.predict_time
     *
     * @return the value of pollutant_analysis2.predict_time
     *
     * @mbggenerated
     */
    public Date getPredictTime() {
        return predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pollutant_analysis2.predict_time
     *
     * @param predictTime the value for pollutant_analysis2.predict_time
     *
     * @mbggenerated
     */
    public void setPredictTime(Date predictTime) {
        this.predictTime = predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutant_analysis2.forcast_time
     *
     * @return the value of pollutant_analysis2.forcast_time
     *
     * @mbggenerated
     */
    public Date getForcastTime() {
        return forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pollutant_analysis2.forcast_time
     *
     * @param forcastTime the value for pollutant_analysis2.forcast_time
     *
     * @mbggenerated
     */
    public void setForcastTime(Date forcastTime) {
        this.forcastTime = forcastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutant_analysis2.forcast_day
     *
     * @return the value of pollutant_analysis2.forcast_day
     *
     * @mbggenerated
     */
    public Integer getForcastDay() {
        return forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pollutant_analysis2.forcast_day
     *
     * @param forcastDay the value for pollutant_analysis2.forcast_day
     *
     * @mbggenerated
     */
    public void setForcastDay(Integer forcastDay) {
        this.forcastDay = forcastDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutant_analysis2.pollutant_group
     *
     * @return the value of pollutant_analysis2.pollutant_group
     *
     * @mbggenerated
     */
    public String getPollutantGroup() {
        return pollutantGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pollutant_analysis2.pollutant_group
     *
     * @param pollutantGroup the value for pollutant_analysis2.pollutant_group
     *
     * @mbggenerated
     */
    public void setPollutantGroup(String pollutantGroup) {
        this.pollutantGroup = pollutantGroup == null ? null : pollutantGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutant_analysis2.pollutant_name
     *
     * @return the value of pollutant_analysis2.pollutant_name
     *
     * @mbggenerated
     */
    public String getPollutantName() {
        return pollutantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pollutant_analysis2.pollutant_name
     *
     * @param pollutantName the value for pollutant_analysis2.pollutant_name
     *
     * @mbggenerated
     */
    public void setPollutantName(String pollutantName) {
        this.pollutantName = pollutantName == null ? null : pollutantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pollutant_analysis2.pollutant_value
     *
     * @return the value of pollutant_analysis2.pollutant_value
     *
     * @mbggenerated
     */
    public String getPollutantValue() {
        return pollutantValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pollutant_analysis2.pollutant_value
     *
     * @param pollutantValue the value for pollutant_analysis2.pollutant_value
     *
     * @mbggenerated
     */
    public void setPollutantValue(String pollutantValue) {
        this.pollutantValue = pollutantValue == null ? null : pollutantValue.trim();
    }

	public String getStationname() {
		return stationname;
	}

	public void setStationname(String stationname) {
		this.stationname = stationname;
	}
}