package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

import java.util.Date;

public class XNForecastModelHourKey {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelHour.timepoint
     *
     * @mbggenerated
     */
    private Date timepoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelHour.stationname
     *
     * @mbggenerated
     */
    private String stationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelHour.CityCode
     *
     * @mbggenerated
     */
    private Integer cityCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelHour.timepoint
     *
     * @return the value of XN_forecastModelHour.timepoint
     *
     * @mbggenerated
     */
    public Date getTimepoint() {
        return timepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelHour.timepoint
     *
     * @param timepoint the value for XN_forecastModelHour.timepoint
     *
     * @mbggenerated
     */
    public void setTimepoint(Date timepoint) {
        this.timepoint = timepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelHour.stationname
     *
     * @return the value of XN_forecastModelHour.stationname
     *
     * @mbggenerated
     */
    public String getStationname() {
        return stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelHour.stationname
     *
     * @param stationname the value for XN_forecastModelHour.stationname
     *
     * @mbggenerated
     */
    public void setStationname(String stationname) {
        this.stationname = stationname == null ? null : stationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelHour.CityCode
     *
     * @return the value of XN_forecastModelHour.CityCode
     *
     * @mbggenerated
     */
    public Integer getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelHour.CityCode
     *
     * @param cityCode the value for XN_forecastModelHour.CityCode
     *
     * @mbggenerated
     */
    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }
}