package xsscd.monitor.air.southwest.modules.job.entitys.mybatis.dto;

public class XNForecastModelDay extends XNForecastModelDayKey {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.ID
     *
     * @mbggenerated
     */
    private Integer iD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.CityName
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.CO
     *
     * @mbggenerated
     */
    private String cO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.NO2
     *
     * @mbggenerated
     */
    private String nO2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.O3_1H
     *
     * @mbggenerated
     */
    private String o31H;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.O3_8H
     *
     * @mbggenerated
     */
    private String o38H;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.SO2
     *
     * @mbggenerated
     */
    private String sO2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.PM10
     *
     * @mbggenerated
     */
    private String pM10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.PM2_5
     *
     * @mbggenerated
     */
    private String pM25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.AQI
     *
     * @mbggenerated
     */
    private String aQI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.PrimaryPollutant
     *
     * @mbggenerated
     */
    private String primaryPollutant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.maxSVR
     *
     * @mbggenerated
     */
    private String maxSVR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.minSVR
     *
     * @mbggenerated
     */
    private String minSVR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.HNO3
     *
     * @mbggenerated
     */
    private String hNO3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.NH3
     *
     * @mbggenerated
     */
    private String nH3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.NOX
     *
     * @mbggenerated
     */
    private String nOX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.EC
     *
     * @mbggenerated
     */
    private String eC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.OC
     *
     * @mbggenerated
     */
    private String oC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.SO4
     *
     * @mbggenerated
     */
    private String sO4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.NO3
     *
     * @mbggenerated
     */
    private String nO3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.NH4
     *
     * @mbggenerated
     */
    private String nH4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.Soil
     *
     * @mbggenerated
     */
    private String soil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.OM
     *
     * @mbggenerated
     */
    private String oM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.avgRH
     *
     * @mbggenerated
     */
    private String avgRH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.accPrecipitation
     *
     * @mbggenerated
     */
    private String accPrecipitation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.avgPressure
     *
     * @mbggenerated
     */
    private String avgPressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.maxPBL
     *
     * @mbggenerated
     */
    private String maxPBL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.avgCloudCover
     *
     * @mbggenerated
     */
    private String avgCloudCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.highTemperature
     *
     * @mbggenerated
     */
    private String highTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.lowTemperature
     *
     * @mbggenerated
     */
    private String lowTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.avgWindSpeed
     *
     * @mbggenerated
     */
    private String avgWindSpeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.domWindDIR
     *
     * @mbggenerated
     */
    private String domWindDIR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XN_forecastModelDay.quality
     *
     * @mbggenerated
     */
    private String quality;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.ID
     *
     * @return the value of XN_forecastModelDay.ID
     *
     * @mbggenerated
     */
    public Integer getiD() {
        return iD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.ID
     *
     * @param iD the value for XN_forecastModelDay.ID
     *
     * @mbggenerated
     */
    public void setiD(Integer iD) {
        this.iD = iD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.CityName
     *
     * @return the value of XN_forecastModelDay.CityName
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.CityName
     *
     * @param cityName the value for XN_forecastModelDay.CityName
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.CO
     *
     * @return the value of XN_forecastModelDay.CO
     *
     * @mbggenerated
     */
    public String getcO() {
        return cO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.CO
     *
     * @param cO the value for XN_forecastModelDay.CO
     *
     * @mbggenerated
     */
    public void setcO(String cO) {
        this.cO = cO == null ? null : cO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.NO2
     *
     * @return the value of XN_forecastModelDay.NO2
     *
     * @mbggenerated
     */
    public String getnO2() {
        return nO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.NO2
     *
     * @param nO2 the value for XN_forecastModelDay.NO2
     *
     * @mbggenerated
     */
    public void setnO2(String nO2) {
        this.nO2 = nO2 == null ? null : nO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.O3_1H
     *
     * @return the value of XN_forecastModelDay.O3_1H
     *
     * @mbggenerated
     */
    public String getO31H() {
        return o31H;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.O3_1H
     *
     * @param o31H the value for XN_forecastModelDay.O3_1H
     *
     * @mbggenerated
     */
    public void setO31H(String o31H) {
        this.o31H = o31H == null ? null : o31H.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.O3_8H
     *
     * @return the value of XN_forecastModelDay.O3_8H
     *
     * @mbggenerated
     */
    public String getO38H() {
        return o38H;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.O3_8H
     *
     * @param o38H the value for XN_forecastModelDay.O3_8H
     *
     * @mbggenerated
     */
    public void setO38H(String o38H) {
        this.o38H = o38H == null ? null : o38H.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.SO2
     *
     * @return the value of XN_forecastModelDay.SO2
     *
     * @mbggenerated
     */
    public String getsO2() {
        return sO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.SO2
     *
     * @param sO2 the value for XN_forecastModelDay.SO2
     *
     * @mbggenerated
     */
    public void setsO2(String sO2) {
        this.sO2 = sO2 == null ? null : sO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.PM10
     *
     * @return the value of XN_forecastModelDay.PM10
     *
     * @mbggenerated
     */
    public String getpM10() {
        return pM10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.PM10
     *
     * @param pM10 the value for XN_forecastModelDay.PM10
     *
     * @mbggenerated
     */
    public void setpM10(String pM10) {
        this.pM10 = pM10 == null ? null : pM10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.PM2_5
     *
     * @return the value of XN_forecastModelDay.PM2_5
     *
     * @mbggenerated
     */
    public String getpM25() {
        return pM25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.PM2_5
     *
     * @param pM25 the value for XN_forecastModelDay.PM2_5
     *
     * @mbggenerated
     */
    public void setpM25(String pM25) {
        this.pM25 = pM25 == null ? null : pM25.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.AQI
     *
     * @return the value of XN_forecastModelDay.AQI
     *
     * @mbggenerated
     */
    public String getaQI() {
        return aQI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.AQI
     *
     * @param aQI the value for XN_forecastModelDay.AQI
     *
     * @mbggenerated
     */
    public void setaQI(String aQI) {
        this.aQI = aQI == null ? null : aQI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.PrimaryPollutant
     *
     * @return the value of XN_forecastModelDay.PrimaryPollutant
     *
     * @mbggenerated
     */
    public String getPrimaryPollutant() {
        return primaryPollutant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.PrimaryPollutant
     *
     * @param primaryPollutant the value for XN_forecastModelDay.PrimaryPollutant
     *
     * @mbggenerated
     */
    public void setPrimaryPollutant(String primaryPollutant) {
        this.primaryPollutant = primaryPollutant == null ? null : primaryPollutant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.maxSVR
     *
     * @return the value of XN_forecastModelDay.maxSVR
     *
     * @mbggenerated
     */
    public String getMaxSVR() {
        return maxSVR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.maxSVR
     *
     * @param maxSVR the value for XN_forecastModelDay.maxSVR
     *
     * @mbggenerated
     */
    public void setMaxSVR(String maxSVR) {
        this.maxSVR = maxSVR == null ? null : maxSVR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.minSVR
     *
     * @return the value of XN_forecastModelDay.minSVR
     *
     * @mbggenerated
     */
    public String getMinSVR() {
        return minSVR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.minSVR
     *
     * @param minSVR the value for XN_forecastModelDay.minSVR
     *
     * @mbggenerated
     */
    public void setMinSVR(String minSVR) {
        this.minSVR = minSVR == null ? null : minSVR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.HNO3
     *
     * @return the value of XN_forecastModelDay.HNO3
     *
     * @mbggenerated
     */
    public String gethNO3() {
        return hNO3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.HNO3
     *
     * @param hNO3 the value for XN_forecastModelDay.HNO3
     *
     * @mbggenerated
     */
    public void sethNO3(String hNO3) {
        this.hNO3 = hNO3 == null ? null : hNO3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.NH3
     *
     * @return the value of XN_forecastModelDay.NH3
     *
     * @mbggenerated
     */
    public String getnH3() {
        return nH3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.NH3
     *
     * @param nH3 the value for XN_forecastModelDay.NH3
     *
     * @mbggenerated
     */
    public void setnH3(String nH3) {
        this.nH3 = nH3 == null ? null : nH3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.NOX
     *
     * @return the value of XN_forecastModelDay.NOX
     *
     * @mbggenerated
     */
    public String getnOX() {
        return nOX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.NOX
     *
     * @param nOX the value for XN_forecastModelDay.NOX
     *
     * @mbggenerated
     */
    public void setnOX(String nOX) {
        this.nOX = nOX == null ? null : nOX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.EC
     *
     * @return the value of XN_forecastModelDay.EC
     *
     * @mbggenerated
     */
    public String geteC() {
        return eC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.EC
     *
     * @param eC the value for XN_forecastModelDay.EC
     *
     * @mbggenerated
     */
    public void seteC(String eC) {
        this.eC = eC == null ? null : eC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.OC
     *
     * @return the value of XN_forecastModelDay.OC
     *
     * @mbggenerated
     */
    public String getoC() {
        return oC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.OC
     *
     * @param oC the value for XN_forecastModelDay.OC
     *
     * @mbggenerated
     */
    public void setoC(String oC) {
        this.oC = oC == null ? null : oC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.SO4
     *
     * @return the value of XN_forecastModelDay.SO4
     *
     * @mbggenerated
     */
    public String getsO4() {
        return sO4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.SO4
     *
     * @param sO4 the value for XN_forecastModelDay.SO4
     *
     * @mbggenerated
     */
    public void setsO4(String sO4) {
        this.sO4 = sO4 == null ? null : sO4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.NO3
     *
     * @return the value of XN_forecastModelDay.NO3
     *
     * @mbggenerated
     */
    public String getnO3() {
        return nO3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.NO3
     *
     * @param nO3 the value for XN_forecastModelDay.NO3
     *
     * @mbggenerated
     */
    public void setnO3(String nO3) {
        this.nO3 = nO3 == null ? null : nO3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.NH4
     *
     * @return the value of XN_forecastModelDay.NH4
     *
     * @mbggenerated
     */
    public String getnH4() {
        return nH4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.NH4
     *
     * @param nH4 the value for XN_forecastModelDay.NH4
     *
     * @mbggenerated
     */
    public void setnH4(String nH4) {
        this.nH4 = nH4 == null ? null : nH4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.Soil
     *
     * @return the value of XN_forecastModelDay.Soil
     *
     * @mbggenerated
     */
    public String getSoil() {
        return soil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.Soil
     *
     * @param soil the value for XN_forecastModelDay.Soil
     *
     * @mbggenerated
     */
    public void setSoil(String soil) {
        this.soil = soil == null ? null : soil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.OM
     *
     * @return the value of XN_forecastModelDay.OM
     *
     * @mbggenerated
     */
    public String getoM() {
        return oM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.OM
     *
     * @param oM the value for XN_forecastModelDay.OM
     *
     * @mbggenerated
     */
    public void setoM(String oM) {
        this.oM = oM == null ? null : oM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.avgRH
     *
     * @return the value of XN_forecastModelDay.avgRH
     *
     * @mbggenerated
     */
    public String getAvgRH() {
        return avgRH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.avgRH
     *
     * @param avgRH the value for XN_forecastModelDay.avgRH
     *
     * @mbggenerated
     */
    public void setAvgRH(String avgRH) {
        this.avgRH = avgRH == null ? null : avgRH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.accPrecipitation
     *
     * @return the value of XN_forecastModelDay.accPrecipitation
     *
     * @mbggenerated
     */
    public String getAccPrecipitation() {
        return accPrecipitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.accPrecipitation
     *
     * @param accPrecipitation the value for XN_forecastModelDay.accPrecipitation
     *
     * @mbggenerated
     */
    public void setAccPrecipitation(String accPrecipitation) {
        this.accPrecipitation = accPrecipitation == null ? null : accPrecipitation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.avgPressure
     *
     * @return the value of XN_forecastModelDay.avgPressure
     *
     * @mbggenerated
     */
    public String getAvgPressure() {
        return avgPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.avgPressure
     *
     * @param avgPressure the value for XN_forecastModelDay.avgPressure
     *
     * @mbggenerated
     */
    public void setAvgPressure(String avgPressure) {
        this.avgPressure = avgPressure == null ? null : avgPressure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.maxPBL
     *
     * @return the value of XN_forecastModelDay.maxPBL
     *
     * @mbggenerated
     */
    public String getMaxPBL() {
        return maxPBL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.maxPBL
     *
     * @param maxPBL the value for XN_forecastModelDay.maxPBL
     *
     * @mbggenerated
     */
    public void setMaxPBL(String maxPBL) {
        this.maxPBL = maxPBL == null ? null : maxPBL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.avgCloudCover
     *
     * @return the value of XN_forecastModelDay.avgCloudCover
     *
     * @mbggenerated
     */
    public String getAvgCloudCover() {
        return avgCloudCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.avgCloudCover
     *
     * @param avgCloudCover the value for XN_forecastModelDay.avgCloudCover
     *
     * @mbggenerated
     */
    public void setAvgCloudCover(String avgCloudCover) {
        this.avgCloudCover = avgCloudCover == null ? null : avgCloudCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.highTemperature
     *
     * @return the value of XN_forecastModelDay.highTemperature
     *
     * @mbggenerated
     */
    public String getHighTemperature() {
        return highTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.highTemperature
     *
     * @param highTemperature the value for XN_forecastModelDay.highTemperature
     *
     * @mbggenerated
     */
    public void setHighTemperature(String highTemperature) {
        this.highTemperature = highTemperature == null ? null : highTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.lowTemperature
     *
     * @return the value of XN_forecastModelDay.lowTemperature
     *
     * @mbggenerated
     */
    public String getLowTemperature() {
        return lowTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.lowTemperature
     *
     * @param lowTemperature the value for XN_forecastModelDay.lowTemperature
     *
     * @mbggenerated
     */
    public void setLowTemperature(String lowTemperature) {
        this.lowTemperature = lowTemperature == null ? null : lowTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.avgWindSpeed
     *
     * @return the value of XN_forecastModelDay.avgWindSpeed
     *
     * @mbggenerated
     */
    public String getAvgWindSpeed() {
        return avgWindSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.avgWindSpeed
     *
     * @param avgWindSpeed the value for XN_forecastModelDay.avgWindSpeed
     *
     * @mbggenerated
     */
    public void setAvgWindSpeed(String avgWindSpeed) {
        this.avgWindSpeed = avgWindSpeed == null ? null : avgWindSpeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.domWindDIR
     *
     * @return the value of XN_forecastModelDay.domWindDIR
     *
     * @mbggenerated
     */
    public String getDomWindDIR() {
        return domWindDIR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.domWindDIR
     *
     * @param domWindDIR the value for XN_forecastModelDay.domWindDIR
     *
     * @mbggenerated
     */
    public void setDomWindDIR(String domWindDIR) {
        this.domWindDIR = domWindDIR == null ? null : domWindDIR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XN_forecastModelDay.quality
     *
     * @return the value of XN_forecastModelDay.quality
     *
     * @mbggenerated
     */
    public String getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XN_forecastModelDay.quality
     *
     * @param quality the value for XN_forecastModelDay.quality
     *
     * @mbggenerated
     */
    public void setQuality(String quality) {
        this.quality = quality == null ? null : quality.trim();
    }
}