package xsscd.monitor.air.southwest.modules.core.entitys.mybatis.dto;

public class SupersetDashboardsAssemblyItem {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly_item.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly_item.dashboards_assembly_id
     *
     * @mbggenerated
     */
    private Long dashboardsAssemblyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly_item.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly_item.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly_item.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly_item.slices_id
     *
     * @mbggenerated
     */
    private String slicesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly_item.on_event
     *
     * @mbggenerated
     */
    private String onEvent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly_item.id
     *
     * @return the value of superset_dashboards_assembly_item.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly_item.id
     *
     * @param id the value for superset_dashboards_assembly_item.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly_item.dashboards_assembly_id
     *
     * @return the value of superset_dashboards_assembly_item.dashboards_assembly_id
     *
     * @mbggenerated
     */
    public Long getDashboardsAssemblyId() {
        return dashboardsAssemblyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly_item.dashboards_assembly_id
     *
     * @param dashboardsAssemblyId the value for superset_dashboards_assembly_item.dashboards_assembly_id
     *
     * @mbggenerated
     */
    public void setDashboardsAssemblyId(Long dashboardsAssemblyId) {
        this.dashboardsAssemblyId = dashboardsAssemblyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly_item.name
     *
     * @return the value of superset_dashboards_assembly_item.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly_item.name
     *
     * @param name the value for superset_dashboards_assembly_item.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly_item.type
     *
     * @return the value of superset_dashboards_assembly_item.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly_item.type
     *
     * @param type the value for superset_dashboards_assembly_item.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly_item.position
     *
     * @return the value of superset_dashboards_assembly_item.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly_item.position
     *
     * @param position the value for superset_dashboards_assembly_item.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly_item.slices_id
     *
     * @return the value of superset_dashboards_assembly_item.slices_id
     *
     * @mbggenerated
     */
    public String getSlicesId() {
        return slicesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly_item.slices_id
     *
     * @param slicesId the value for superset_dashboards_assembly_item.slices_id
     *
     * @mbggenerated
     */
    public void setSlicesId(String slicesId) {
        this.slicesId = slicesId == null ? null : slicesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly_item.on_event
     *
     * @return the value of superset_dashboards_assembly_item.on_event
     *
     * @mbggenerated
     */
    public String getOnEvent() {
        return onEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly_item.on_event
     *
     * @param onEvent the value for superset_dashboards_assembly_item.on_event
     *
     * @mbggenerated
     */
    public void setOnEvent(String onEvent) {
        this.onEvent = onEvent == null ? null : onEvent.trim();
    }
}