package xsscd.monitor.air.southwest.modules.core.entitys.mybatis.dto;

import java.util.List;

public class SupersetDashboardsAssembly {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly.dashboards_id
     *
     * @mbggenerated
     */
    private Long dashboardsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superset_dashboards_assembly.slices_id
     *
     * @mbggenerated
     */
    private String slicesId;

    private List<SupersetDashboardsAssemblyItem> supersetDashboardsAssemblyItems;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly.id
     *
     * @return the value of superset_dashboards_assembly.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly.id
     *
     * @param id the value for superset_dashboards_assembly.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly.dashboards_id
     *
     * @return the value of superset_dashboards_assembly.dashboards_id
     *
     * @mbggenerated
     */
    public Long getDashboardsId() {
        return dashboardsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly.dashboards_id
     *
     * @param dashboardsId the value for superset_dashboards_assembly.dashboards_id
     *
     * @mbggenerated
     */
    public void setDashboardsId(Long dashboardsId) {
        this.dashboardsId = dashboardsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly.name
     *
     * @return the value of superset_dashboards_assembly.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly.name
     *
     * @param name the value for superset_dashboards_assembly.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly.type
     *
     * @return the value of superset_dashboards_assembly.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly.type
     *
     * @param type the value for superset_dashboards_assembly.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly.position
     *
     * @return the value of superset_dashboards_assembly.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly.position
     *
     * @param position the value for superset_dashboards_assembly.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superset_dashboards_assembly.slices_id
     *
     * @return the value of superset_dashboards_assembly.slices_id
     *
     * @mbggenerated
     */
    public String getSlicesId() {
        return slicesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superset_dashboards_assembly.slices_id
     *
     * @param slicesId the value for superset_dashboards_assembly.slices_id
     *
     * @mbggenerated
     */
    public void setSlicesId(String slicesId) {
        this.slicesId = slicesId == null ? null : slicesId.trim();
    }

    public List<SupersetDashboardsAssemblyItem> getSupersetDashboardsAssemblyItems() {
        return supersetDashboardsAssemblyItems;
    }

    public void setSupersetDashboardsAssemblyItems(List<SupersetDashboardsAssemblyItem> supersetDashboardsAssemblyItems) {
        this.supersetDashboardsAssemblyItems = supersetDashboardsAssemblyItems;
    }
}